### ISSUE TITLE
Ability to collapse subcategories in the sidebar

### ISSUE THREAD

**Issue by awbait** [vuejs/vitepress#1493] opened 2022-10-16 09:06 UTC
### Is your feature request related to a problem? Please describe.

Hey! With a very large sidebar, navigation becomes inconvenient.
![image](https://user-images.githubusercontent.com/12417799/196027162-294ce8b8-8d24-4eb3-bfe6-032d991990f5.png)

### Describe the solution you'd like

Need to be able to collapse subcategories. As an option, add the ability to use the collapsible and collapsed tags included in subitems.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-10-16 09:23
Duplicate of #1360

**Closed by brc-dd** 2022-10-16 09:23 UTC
