### ISSUE TITLE
Serial number report error duplicate attribute

### ISSUE THREAD

**Issue by think2cat** [vuejs/vitepress#4043] opened 2024-07-14 09:34 UTC
### Describe the bug

```
1. **every**，判断是否所有元素都符合，需要每个都为true才返回true，否则返回false
2. **some**，判断是否有元素符合，一旦遇到true则停止
3. **map**，每个元素按function返回结果构成新数组
4. **filter**，返回所有符合条件的元素构成的新数组
5. **forEach**，单独执行每个元素，无返回
```

x Build failed in 38.07s
✖ building client + server bundles...
build error:
[vite:vue] [plugin vite:vue] docs/web/Javascript数组.md (4:88): Duplicate attribute.       
file: C:/git/21ido.com_vite/docs/web/Javascript数组.md:4:88
[vite:vue] [plugin vite:vue] docs/web/Javascript数组.md (4:88): Duplicate attribute.       
file: C:/git/21ido.com_vite/docs/web/Javascript数组.md:4:88
SyntaxError: Duplicate attribute.
    at createCompilerError (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1325:17)
    at emitError (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2788:5)
    at Object.onattribnameend (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2299:7)
    at Tokenizer.handleAttrNameEnd (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:876:14)
    at Tokenizer.stateInAttrName (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:816:12)
    at Tokenizer.parse (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1067:16)
    at Object.baseParse (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2820:13)
    at Object.parse (C:\git\21ido.com_vite\node_modules\@vue\compiler-dom\dist\compiler-dom.cjs.prod.js:633:23)
    at Object.parse$2 [as parse] (C:\git\21ido.com_vite\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:1853:24)
    at createDescriptor (file:///C:/git/21ido.com_vite/node_modules/@vitejs/plugin-vue/dist/index.mjs:64:43)
error Command failed with exit code 1.

---

```
* **跑步鞋**，李宁的猫爪2代野外跑鞋，跑步爬山两不误
* **蓝魔新V3**，30小时连续播放，加森海塞尔MX70运动耳塞
* **Suunto T1心率表**，用了之后才知道我心率真TMD快。{% post_link 'Digital/Suunto_T1使用感受' %}
* **极地贴身腰包**，跑步时再也不用担心钥匙手机会在裤袋摇来晃去了，很实用
* **方巾**，绑在手上可以擦汗
```

[vite:vue] [plugin vite:vue] docs/Life/慢跑装备08年版.md (8:47): Duplicate attribute.      
file: C:/git/21ido.com_vite/docs/Life/慢跑装备08年版.md:8:47
SyntaxError: Duplicate attribute.
    at createCompilerError (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1325:17)
    at emitError (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2788:5)
    at Object.onattribnameend (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2299:7)
    at Tokenizer.handleAttrNameEnd (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:876:14)
    at Tokenizer.stateInAttrName (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:816:12)
    at Tokenizer.parse (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:1067:16)
    at Object.baseParse (C:\git\21ido.com_vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.prod.js:2820:13)
    at Object.parse (C:\git\21ido.com_vite\node_modules\@vue\compiler-dom\dist\compiler-dom.cjs.prod.js:633:23)
    at Object.parse$2 [as parse] (C:\git\21ido.com_vite\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:1853:24)
    at createDescriptor (file:///C:/git/21ido.com_vite/node_modules/@vitejs/plugin-vue/dist/index.mjs:64:43)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 

### Reproduction

Using a sequence followed by bold text will result in an error message

### Expected behavior

Can be nested for use

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.42 GB / 15.86 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.67)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    vitepress: 1.2.3 => 1.2.3
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-07-14 09:53
This should be quoted with backticks:

``` `{% post_link 'Digital/Suunto_T1使用感受' %}` ```

If you don't want to quote that, set markdown.attrs.disable to false in your vitepress config.

Duplicate of #664, #662, #629, #449, #1781, #1817, #3401

**Closed by brc-dd** 2024-07-14 09:53 UTC
Labels: bug: pending triage

**Comment by think2cat** [comment] 2024-07-16 15:08
> This should be quoted with backticks:
> 
> `` `{% post_link 'Digital/Suunto_T1使用感受' %}` ``
> 
> If you don't want to quote that, set markdown.attrs.disable to true in your vitepress config.
> 
> Duplicate of #664, #662, #629, #449, #1781, #1817, #3401

```
1. **every**，判断是否所有元素都符合，需要每个都为true才返回true，否则返回false
2. **some**，判断是否有元素符合，一旦遇到true则停止
3. **map**，每个元素按function返回结果构成新数组
4. **filter**，返回所有符合条件的元素构成的新数组
5. **forEach**，单独执行每个元素，无返回
```

also error, replace the `123` to `*`, error again
