### ISSUE TITLE
render `__VP_STATIC_START__`

### ISSUE THREAD

**Issue by userquin** [vuejs/vitepress#420] opened 2021-10-17 13:06 UTC
### Describe the bug

original closed from
- #417

`__VP_STATIC_END__` is also at bottom of the page.

### Reproduction

It is random, between builds, sometimes `__VP_STATIC_START__` and  `__VP_STATIC_END__` will be shown, sometimes no.

I added some `md` files and forgot to add the `frontmatter` title, it seems adding it will fix the problem, but now it is there again.

If we do a hard refresh on page that's showing the `__VP_STATIC_START__` will dissapear, but navigating to another page and back it again `__VP_STATIC_START__` will be displayed.

The app is a pwa, but the problem is on the genetared html page, seems there is 2 versions of the md page js, `xxx.js` and `xxx.lean.js`. When the app is loaded using the `xxx.lean.js` version, then `__VP_STATIC_START__` and  `__VP_STATIC_END__` will be shown.

The repo is here: https://github.com/antfu/vite-plugin-pwa

I'm using node 15, but should work also with 14.

The `vitepress` app can be found on `docs` package on the repo.

To test you will need latest `pnpm` installed globally, to generate the `vitepress docs`:
1) clone the repo or download the zip
2) execute `pnpm install && pnpm run build` from root folder
3) run the app
- to start dev, execute `pnpm run docs` from root folder
- to build and run the docs, execute `pnpm run docs:serve` from root folder

### Expected behavior

`__VP_STATIC_START__` and `__VP_STATIC_END__` should not be displayed.

### System Info
Using `vitepress` version `0.19.2`.

On dev machine:

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 49.91 GB / 63.95 GB
  Binaries:
    Node: 15.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 94.0.4606.81
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.50)
    Internet Explorer: 11.0.19041.1202
```
The app is deployed on `netlify`.

### Additional context

You can test the app on a private window and so the pwa will not interfere with the problem.

**TO REPRODUCE THE PROBLEM ON PRODUCTION**

The current page with the problem is: https://vite-plugin-pwa.netlify.app/guide/generate.html

You can do a hard refresh and check `generate.html` page to see the `guide_generate.md.25c0e6c1.lean.js` is loaded, once the `__VP_STATIC_START__` is shown, clear the network panel, navigate to another page and refresh, clean network panel again, and then back to `Generate Service Worker`, you will see it is using  `guide_generate.md.25c0e6c1.js` instead the `lean js` version, and `__VP_STATIC_START__` is gone.

If you copy/paste the `js` files for `guide_generate.md.xxx.js` you will see that on lean version there is `__VP_STATIC_START__`.

A screenshot with the problem on deployed app (https://vite-plugin-pwa.netlify.app/guide/generate.html):

![imagen](https://user-images.githubusercontent.com/6311119/137627748-760af892-453a-4ce7-8f7b-afb162a51286.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by 0x009922** [comment] 2021-11-02 09:01
I have a deployed non-random example of this bug here: https://soramitsu.github.io/scale-codec-js-library/guide/core.html

**Comment by aantipov** [comment] 2021-11-03 07:32
+1 same issue here. 
It seems the issue has been fixed, but the new version has not been released yet.

**Comment by aantipov** [comment] 2021-11-10 11:22
I see the issue affects the vitepress docs as well:
![CleanShot 2021-11-10 at 12 17 10@2x](https://user-images.githubusercontent.com/427621/141103833-7966f488-8b30-4326-8964-77b4fa431643.png)

Steps to reproduce:
1. Loas https://vitepress.vuejs.org/guide/frontmatter.html ("Frontmatter" in Navbar is highlighted)
2. Click on "Theming" in Navbar
3. Click on "Frontmatter" in Navbar
![CleanShot 2021-11-10 at 12 20 48](https://user-images.githubusercontent.com/427621/141104392-d19d088d-173e-4d06-bafc-f0b83e4a4645.gif)

**Comment by ulivz** [comment] 2021-11-28 09:01
+1

**Comment by kagol** [comment] 2021-12-07 09:11
+1
I had the same problem

**Comment by yyx990803** [comment] 2022-01-06 03:15
This should have been fixed by https://github.com/vuejs/vitepress/commit/dfa7c0525f010994437acb060867d9ca1572867d since it can no longer be reproduced on VitePress' own docs.

**Closed by yyx990803** 2022-01-06 03:15 UTC
Labels: bug: pending triage
