### ISSUE TITLE
index.md

### ISSUE THREAD

**Issue by myzf** [vuejs/vitepress#3409] opened 2024-01-05 03:01 UTC
### Describe the bug

index.md not support markdown

### Reproduction

"I'm encountering an issue with VitePress where Markdown syntax in my index.md file doesn't seem to apply the expected styles on the homepage, whereas in VuePress, this works as anticipated. For instance, if I wish to include some introductory text on the main page and then guide users to the navigation bar, it appears that I need to manually write the CSS styles. Why can't I utilize Markdown for styling in this case?"

### Expected behavior

"I'm encountering an issue with VitePress where Markdown syntax in my index.md file doesn't seem to apply the expected styles on the homepage, whereas in VuePress, this works as anticipated. For instance, if I wish to include some introductory text on the main page and then guide users to the navigation bar, it appears that I need to manually write the CSS styles. Why can't I utilize Markdown for styling in this case?"

### System Info

```Text
"I'm encountering an issue with VitePress where Markdown syntax in my index.md file doesn't seem to apply the expected styles on the homepage, whereas in VuePress, this works as anticipated. For instance, if I wish to include some introductory text on the main page and then guide users to the navigation bar, it appears that I need to manually write the CSS styles. Why can't I utilize Markdown for styling in this case?"
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-01-05 04:18
Duplicate of #800

**Closed by brc-dd** 2024-01-05 04:18 UTC
Labels: bug: pending triage
