### ISSUE TITLE
searchbox

### ISSUE THREAD

**Issue by YongZhennj** [vuejs/vitepress#3589] opened 2024-02-21 04:50 UTC
### Describe the bug

Click on the search box and the page will look right offset，This problem also exists in Vue，This is caused by the scroll bar on the right。

### Reproduction

Click on the search box.

### Expected behavior

Click the search box, the page does not offset

### System Info

```Text
all
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-03-16 07:27
Duplicate of #1054

**Closed by brc-dd** 2024-03-16 07:27 UTC
