### ISSUE TITLE
Page hangs on dev local search

### ISSUE THREAD

**Issue by lslzl3000** [vuejs/vitepress#2306] opened 2023-04-28 04:19 UTC
### Describe the bug

I have over 1000+ mds to search, when I try to use local search on dev environment,  the page will hang/freeze after input something, it cloud show 15 results on first input letter though, then the page hangs. No error in browser log or node log

But after build, the search works fine with 1000+ files. 

### Reproduction

1. it may need lots of docs to test, e.g. 1000+ mds
2. just input something in local search dialog, it will show first 15 results, then everything freeze
3. have to force exit browser

but it works fine after build

### Expected behavior

the dev environment should work fine, at least not hang the page process

### System Info

```sh
MacOS 13.3
vitepress 1.0.0-alpha.74
Chrome 115.0.5737.0
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-04-30 11:50
Duplicate of #2262

**Closed by brc-dd** 2023-04-30 11:50 UTC
Labels: build
