### ISSUE TITLE
break with `{String|RegExp|Object|Function}`

### ISSUE THREAD

**Issue by atian25** [vuejs/vitepress#629] opened 2022-05-19 10:13 UTC
### Describe the bug

```bash
$ npm run docs:dev
```

when `README.md` includes some string like `{String|RegExp|Object|Function}`

got error:

```bash
DOMException: Failed to execute 'setAttribute' on 'Element': 'String|RegExp|Object|Function' is not a valid attribute name.
```

### Reproduction

```markdown
### wait(type, expected)

Wait for your expectations to pass. It's useful for testing long-run apps such as build tools or http servers.

- `type`: {String} - support `message` / `stdout` / `stderr` / `close`
- `expected`: {String|RegExp|Object|Function}
```

### Expected behavior

work fine.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 63.44 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/Library/Caches/fnm_multishells/1367_1652147272868/bin/node
    npm: 8.5.0 - ~/Library/Caches/fnm_multishells/1367_1652147272868/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment] 2022-05-19 10:19
Thanks for the report! Confirmed. This still happens on `next` branch as well. Not sure why, but need to look into it.

**Comment by atian25** [comment] 2022-05-26 09:19
I think, in most of cases,  the documentation does not need this feature, so is it possible to provide a configuration?

**Comment by atian25** [comment] 2022-05-26 09:20
> I think, in most of cases, the documentation does not need this feature, and it's hard for the document author to figure up what has happen, so is it possible to provide a configuration to enable/disable this feature?

**Comment by kiaking** [comment] 2022-05-26 09:23
Ohhh how awesoe are you!? I didn't see `markdown-it-attrs` there 😅 You're correct, and seems like the plugin don't accept `|`. So `{String}` works, but not `{String|}`.

I think we should document what Markdown-it Plugin VitePress uses at least. Though it would be a bit hard for users to find out the cause if someone ever run into this 🤔 

Maybe we should have "Caveat" section or something and list these kind of edge cases.

Also let's provide a option to turn off this feature 👍 

I've added doc todo at https://github.com/vuejs/vitepress/issues/643.

For this issue, I'll create a another issue for adding disable option for `markdown-it-attrs` 👍

**Comment by kiaking** [comment] 2022-05-26 09:28
Closing this issue since this is not a bug. Follow up on https://github.com/vuejs/vitepress/issues/662

**Closed by kiaking** 2022-05-26 09:28 UTC

**Comment by brc-dd** [comment] 2022-05-26 10:25
Disabling it will break a whole lot of things.

**Comment by kiaking** [comment] 2022-05-26 10:32
Oh, are we using it internally?

**Comment by brc-dd** [comment] 2022-05-26 10:52
@kiaking Line highlighting in code blocks needs it for some thing. Not exactly sure what.

**Comment by kiaking** [comment] 2022-05-26 11:10
Hmmm, good to know. Thanks! If this is the only place, I think it wouldn't cost that match to patch this code.

Let's not forget about this when working on with the issue!

**Comment by brc-dd** [comment] 2022-05-26 11:24
On second look, it might be easier. This code should work if that plugin is disabled:

https://github.com/vuejs/vitepress/blob/9f1b2b1ae2cae93e46c5c9259d51aadaaeee9cc5/src/node/markdown/plugins/highlightLines.ts#L1-L28
