### ISSUE TITLE
Duplicate sidebar in build not dev

### ISSUE THREAD

**Issue by austinginder** [vuejs/vitepress#177] opened 2020-12-05 15:14 UTC
Attempting to do a very basic VitePress site and the build looks different then dev. For some reason the build is duplicating the sidebar and page navigation sections.

`yarn docs:dev`

![Screenshot from 2020-12-05 10-09-22](https://user-images.githubusercontent.com/110346/101246584-47cc1d00-36e2-11eb-9db0-b5db179c7b4e.png)

 `yarn docs:build` and  `yarn docs:serve`

![Screenshot from 2020-12-05 10-09-11](https://user-images.githubusercontent.com/110346/101246589-4ef32b00-36e2-11eb-95dc-4d4c188bf4ca.png)

**To Reproduce**
Follow the steps listed here: https://vitepress.vuejs.org/guide/getting-started.html then add a basic sidebar to `docs/.vitpress/config.js` like this.

```
module.exports = {
  themeConfig: {
      sidebar: {
          '/': [
              {
                text: 'Introduction',
                children: [
                  { text: 'Introduction', link: '/' },
                  { text: 'Getting Started', link: '/guide/' },
                ]
              }
            ]
      }
  }
}
```

**Expected behavior**
Would expect `yarn docs:dev` to look the same as `yarn docs:build` and `yarn docs:serve`.

**System Info**
- vitepress version: v0.9.1
- vite version: v1.0.0-rc.13
- Node version: v12.18.2
- OS version: Pop!_OS 20.10

**Comment by zhouxinyong** [comment] 2020-12-08 12:25
the same issue +1

**Comment by lukeromanowicz** [comment] 2020-12-16 08:59
+1, reproduced here: https://github.com/lukeromanowicz/vitepress-issues/tree/issue/duplicated-content-in-prod-build
Vitepress: 0.9.2
Node: 14LTS

**Comment by fotijr** [comment] 2020-12-17 02:03
I've replicated this in versions 0.9.0, 0.8.1, 0.8.0, 0.7.4, 0.7.3, and 0.7.2. Version 0.7.1 failed to build with a "MODULE_NOT_FOUND" error (for my setup, at least).

Could this bug be caused by a dependency? I'd be surprised if this behavior has been in the last month of releases.

**Comment by lukeromanowicz** [comment] 2020-12-17 09:11
@fotijr you are absolutely right.

A quick workaround is to downgrade Vue dependency from 3.0.4 to 3.0.3. In yarn it would be:

```
  "resolutions": {
    "vitepress/**/vue": "3.0.3",
    "vitepress/@vue/compiler-sfc": "3.0.3",
    "vitepress/@vue/server-renderer": "3.0.3"
  },
```

**Comment by fotijr** [comment] 2020-12-17 13:57
Awesome workaround, thanks for sharing @lukeromanowicz! Confirmed this resolved the issue for me.

Anyone know what or where the root issue is?

**Comment by haochenli** [comment] 2020-12-23 03:01
If you dig into the `.vitepress/dist/index.html` file generated by the command `docs: build`, you will see in the body tag there is a dom section and a script section, if you delete one of them, the result will be correct. So I guess in the script module, the vitepress append the dom section again.
![img](https://user-images.githubusercontent.com/14314849/102954012-90227200-450d-11eb-9f9f-85adbee9a6b0.jpg)

Besides, do we need a PR to fix that? I would be glad to do that.

**Comment by posva** [comment] 2021-01-04 12:27
This was fixed in the latest vitepress version

**Closed by posva** 2021-01-04 12:27 UTC
Labels: bug
