### ISSUE TITLE
The markdown.theme.xxx theme is not displayed correctly in light mode

### ISSUE THREAD

**Issue by keer-tea** [vuejs/vitepress#3261] opened 2023-11-26 06:41 UTC
### Describe the bug

Why does the markdown.theme.xxx theme setting not take effect. I configured the theme for the markdown as follows.
```js
export default defineConfig({
  markdown: {
    theme: {
      light: 'dark-plus',
      dark: 'dark-plus',
    }
  },
})
````
but only correctly displayed the theme in dark mode, 
![image](https://github.com/vuejs/vitepress/assets/77321887/c1ab87fe-a365-4157-9cab-b3a1d792314b)

while the background of the code block turned white in light mode. 

![image](https://github.com/vuejs/vitepress/assets/77321887/bfc6aca8-43aa-416e-8e25-e9ad9432ad26)

What I hope is that the background of the code blocks in dark and light modes is black.

### Reproduction

https://stackblitz.com/edit/vite-axs5w5?file=docs%2F.vitepress%2Fconfig.ts,docs%2Findex.md,docs%2Fexample.md

### Expected behavior

If I explicitly set `markdown.theme` as only one theme, the color of the code block should be displayed consistently in dark and light modes

### System Info

```Text
System:
    OS: Windows 11 10.0.22621
    CPU: (32) x64 AMD Ryzen 9 7945HX with Radeon Graphics
    Memory: 19.24 GB / 31.69 GB
  Binaries:
    Node: 18.18.0 - D:\myDownload\nodejs\node.EXE
    npm: 9.8.1 - D:\myDownload\nodejs\npm.CMD
    pnpm: 8.7.6 - D:\myDownload\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.72)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-rc.31 => 1.0.0-rc.31
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-11-26 08:42
Duplicate of https://github.com/vuejs/vitepress/issues/3154#issuecomment-1784612839

**Closed by brc-dd** 2023-11-26 08:42 UTC
Labels: bug: pending triage
