### ISSUE TITLE
Will local full-text search be added in the future?

### ISSUE THREAD

**Issue by arcqiufeng** [vuejs/vitepress#1505] opened 2022-10-19 06:22 UTC
### Is your feature request related to a problem? Please describe.

I'm writing an internal manual by vitepress, a web server was set up in LAN. 
For user manuals, full-text search is an important feature. 

My doubt is that the 'search' section of official VitePress guide is blank.
Will search functionality be externally hosted or implemented internally in future?

Is there a formal official roadmap to tell us if this will realize in the future?

### Describe the solution you'd like

Have a local search solution formally in future.

### Describe alternatives you've considered

Switch to vuepress?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-10-19 06:31
Duplicate of #670

Try https://github.com/vuejs/vitepress/issues/670#issuecomment-1242594777

**Closed by brc-dd** 2022-10-19 06:31 UTC

**Comment by arcqiufeng** [comment] 2022-10-19 06:41
It's not accurate to say it's duplicated.  https://github.com/vuejs/vitepress/issues/670 is how to do that.

Because I'm just a non-programmer, non-developer user. I only use it. 

So I need to know simply and clearly whether the official will implement it, rather than asking for help here on how to hack this feature.

Can there be a clear statement given by the VitePress manager?

Will it be or not be.

**Comment by arcqiufeng** [comment] 2022-10-19 06:42
Or I have to use vuepress?

**Comment by e3d** [comment] 2022-10-22 02:54
really it is a key missing feature.

**Comment by isuke01** [comment] 2022-11-18 21:39
Yep, agree. Without search it is pointless.
