### ISSUE TITLE
Possibility of building with missing assets

### ISSUE THREAD

**Issue by personalsoft-fabianobonin** [vuejs/vitepress#3085] opened 2023-10-13 14:43 UTC
### Is your feature request related to a problem? Please describe.

I manage a team responsible for generating documentation, and we have an automated build process triggered by a GitHub webhook. If any of my team members accidentally push a page with an invalid asset, it halts the entire documentation build process.

You already have the option "ignoreDeadLinks", so a inconsistent build is already a possibility taken into account by your developer team. If we can have broken links, why can't we have broken assets? Current behavior seems inconsistent.

### Describe the solution you'd like

Some way to build my site, even if there are inconsistencies in the documentation or assets.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-10-14 07:46
Please avoid creating multiple issues asking the same thing.

Duplicate of #3081

**Closed by brc-dd** 2023-10-14 07:46 UTC
