### ISSUE TITLE
Local search can be support?

### ISSUE THREAD

**Issue by mouyong** [vuejs/vitepress#1757] opened 2023-01-04 06:04 UTC
### Is your feature request related to a problem? Please describe.

hope can be support local search. when run `docs:dev`, current doesn't have search functional.

### Describe the solution you'd like

hope can use local search like vuepress: https://v2.vuepress.vuejs.org/reference/plugin/search.html

this is an local search js:

https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/plugin-search/match-query.js

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-01-04 06:57
Duplicate of #670

**Closed by brc-dd** 2023-01-04 06:57 UTC
