### ISSUE TITLE
Included image filename contains space will make build fail

### ISSUE THREAD

**Issue by Jeff-Tian** [vuejs/vitepress#2596] opened 2023-07-09 10:59 UTC
### Describe the bug

In dev mode, both image filenames contain space or not will serve fine:

<img width="1282" alt="image" src="https://github.com/vuejs/vitepress/assets/3367820/acc1113c-6f46-4f0f-abd2-b3a0936792a9">

But the build will fail when met the image assets whose filename contains space:

<img width="1202" alt="image" src="https://github.com/vuejs/vitepress/assets/3367820/329c0a68-86f5-4239-abfb-4335227e6de6">

### Reproduction

See https://stackblitz.com/edit/vite-upxxuh?file=docs%2Fbook%2Fresources%2Ftest%20(1).svg,docs%2Findex.md,docs%2Fbook%2Fresources%2Ftest.svg,

add a image filename contains space and build.

### Expected behavior

Build should succeed.

Ideally should `decodeURIComponent` when converting `![](image%20(1).png]` to code. 

So the converted code should be like `import image from  "image (1).png"` instead of `import image from  "image%20(1).png"`.

### System Info

```sh
❯ npx envinfo --system --npmPackages vitepress --binaries --browsers


Need to install the following packages:
  envinfo@7.10.0
Ok to proceed? (y) y

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.3 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: v1.0.0-beta.5 => 1.0.0-beta.5
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-07-09 11:04
Duplicate of #573

**Closed by brc-dd** 2023-07-09 11:04 UTC
Labels: bug: pending triage
