### ISSUE TITLE
markdown parse error

### ISSUE THREAD

**Issue by webpon** [vuejs/vitepress#1817] opened 2023-01-20 07:31 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/50807258/213641051-e53c90d1-77dc-4e6a-a07f-d25b5a72db37.png)

### Reproduction

1

### Expected behavior

11

### System Info

```shell
1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-01-20 07:43
Duplicate of #664, #662, #629, #449, #1781

**Closed by brc-dd** 2023-01-20 07:43 UTC
Labels: bug: pending triage

**Comment by webpon** [comment] 2023-01-20 17:08
> Duplicate of #664, #662, #629, #449, #1781

thank you
