### ISSUE TITLE
What about using markdown extension syntax for multilingual translation?

### ISSUE THREAD

**Issue by ajiho** [vuejs/vitepress#4106] opened 2024-08-06 08:02 UTC
### Is your feature request related to a problem? Please describe.

I have reviewed the relevant parts of the document repeatedly, and I only found that it supports global setting of one language.

Although you can do your own translation later, it may seem a bit troublesome

```
::: info 信息
This is an info box.
:::

::: tip 提示
This is a tip.
:::
```

The advantages of using it this way are verbose

### Describe the solution you'd like

```js
themeConfig:{
          logo: { src: "/logo-mini.svg", width: 24, height: 24 },
           markdown: {
            container: {
                locales: {
                    root: {
                        tipLabel: "提示",
                        warningLabel: "警告",
                        dangerLabel: "危险",
                        infoLabel: "信息",
                        detailsLabel: "详细信息",
                    },
                    en:{
                        tipLabel: "Tip",
                        warningLabel: "Warning",
                        //...
                    }
                },
            },
        },
}
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-08-06 08:28
Duplicate of #3861

**Closed by brc-dd** 2024-08-06 08:28 UTC
