### ISSUE TITLE
`vitepress build` hangs after a successful build

### ISSUE THREAD

**Issue by mxmul** [vuejs/vitepress#84] opened 2020-09-11 21:12 UTC
**Describe the bug**
With a single markdown file (like the example in the README), vitepress successfully builds but the process never exits.

**To Reproduce**

```bash
$ mkdir repro
$ cd repro
$ echo '# Hello VitePress' > index.md
$ npx vitepress build
vitepress v0.5.0
vite v1.0.0-rc.4
building client bundle...
building server bundle...
rendering pages...
done.

# (it hangs here)
```

**Expected behavior**
The process should exit with status code zero.

**System Info**
- vitepress version: v0.5.0
- vite version: v1.0.0-rc.4
- Node version: v12.18.3
- OS version: macOS 10.15.6 (but this also repros in a netlify deploy)

**Additional context**

I used [why-is-node-running](https://www.npmjs.com/package/why-is-node-running) to detect open handles, and it appears that vite/vitepress leaves a bunch of esbuild processes running.

<details>
  <summary>Full output from why-is-node-running</summary>

```bash

$ ./node_modules/.bin/why-is-node-running ./node_modules/.bin/vitepress build
probing program /Users/mmulder/repro/node_modules/.bin/vitepress
kill -SIGUSR1 11013 for logging
vitepress v0.5.0
vite v1.0.0-rc.4
building client bundle...
building server bundle...
rendering pages...
done.
load: 3.57  cmd: esbuild 11024 running 0.00u 0.00s
There are 14 handle(s) keeping the process running

# TTYWRAP
/Users/mmulder/repro/node_modules/siginfo/index.js:3               - if (process.stderr.isTTY || force === true) {
/Users/mmulder/repro/node_modules/why-is-node-running/include.js:3 - require('siginfo')(why, true)

# SIGNALWRAP
/Users/mmulder/repro/node_modules/siginfo/index.js:3               - if (process.stderr.isTTY || force === true) {
/Users/mmulder/repro/node_modules/why-is-node-running/include.js:3 - require('siginfo')(why, true)

# SIGNALWRAP
/Users/mmulder/repro/node_modules/siginfo/index.js:5               - process.on('SIGINFO', onsiginfo)
/Users/mmulder/repro/node_modules/why-is-node-running/include.js:3 - require('siginfo')(why, true)

# SIGNALWRAP
/Users/mmulder/repro/node_modules/siginfo/index.js:6               - process.on('SIGUSR1', onsiginfo)
/Users/mmulder/repro/node_modules/why-is-node-running/include.js:3 - require('siginfo')(why, true)

# TTYWRAP
/Users/mmulder/repro/node_modules/chalk/node_modules/supports-color/index.js:129 - stdout: getSupportLevel(process.stdout),

# PROCESSWRAP
/Users/mmulder/repro/node_modules/esbuild/lib/main.js:543                       - let child = child_process.spawn(command, args.concat("--service"), {
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:39           - _service = await esbuild_1.startService();
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:49           - const service = await ensureService();
/Users/mmulder/repro/node_modules/vite/dist/node/build/buildPluginEsbuild.js:38 - return esbuildService_1.transform(code, chunk.fileName, {
/Users/mmulder/repro/node_modules/rollup/dist/shared/rollup.js:18616            - return hook.apply(context, args);

# PIPEWRAP
/Users/mmulder/repro/node_modules/esbuild/lib/main.js:543             - let child = child_process.spawn(command, args.concat("--service"), {
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:39 - _service = await esbuild_1.startService();
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:49 - const service = await ensureService();

# PIPEWRAP
/Users/mmulder/repro/node_modules/esbuild/lib/main.js:543             - let child = child_process.spawn(command, args.concat("--service"), {
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:39 - _service = await esbuild_1.startService();
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:49 - const service = await ensureService();

# PROCESSWRAP
/Users/mmulder/repro/node_modules/esbuild/lib/main.js:543                       - let child = child_process.spawn(command, args.concat("--service"), {
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:39           - _service = await esbuild_1.startService();
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:49           - const service = await ensureService();
/Users/mmulder/repro/node_modules/vite/dist/node/build/buildPluginEsbuild.js:38 - return esbuildService_1.transform(code, chunk.fileName, {
/Users/mmulder/repro/node_modules/rollup/dist/shared/rollup.js:18616            - return hook.apply(context, args);

# PIPEWRAP
/Users/mmulder/repro/node_modules/esbuild/lib/main.js:543             - let child = child_process.spawn(command, args.concat("--service"), {
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:39 - _service = await esbuild_1.startService();
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:49 - const service = await ensureService();

# PIPEWRAP
/Users/mmulder/repro/node_modules/esbuild/lib/main.js:543             - let child = child_process.spawn(command, args.concat("--service"), {
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:39 - _service = await esbuild_1.startService();
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:49 - const service = await ensureService();

# PROCESSWRAP
/Users/mmulder/repro/node_modules/esbuild/lib/main.js:543                       - let child = child_process.spawn(command, args.concat("--service"), {
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:39           - _service = await esbuild_1.startService();
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:49           - const service = await ensureService();
/Users/mmulder/repro/node_modules/vite/dist/node/build/buildPluginEsbuild.js:38 - return esbuildService_1.transform(code, chunk.fileName, {
/Users/mmulder/repro/node_modules/rollup/dist/shared/rollup.js:18616            - return hook.apply(context, args);

# PIPEWRAP
/Users/mmulder/repro/node_modules/esbuild/lib/main.js:543             - let child = child_process.spawn(command, args.concat("--service"), {
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:39 - _service = await esbuild_1.startService();
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:49 - const service = await ensureService();

# PIPEWRAP
/Users/mmulder/repro/node_modules/esbuild/lib/main.js:543             - let child = child_process.spawn(command, args.concat("--service"), {
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:39 - _service = await esbuild_1.startService();
/Users/mmulder/repro/node_modules/vite/dist/node/esbuildService.js:49 - const service = await ensureService();
```

</details>

**Comment by posva** [comment] 2020-09-16 07:36
Duplicate of https://github.com/vuejs/vitepress/issues/64

**Closed by posva** 2020-09-16 07:36 UTC
Labels: bug: pending triage

**Comment by zigomir** [comment] 2020-09-19 09:20
@posva this started happening for me only in `v0.6.0` which has been released two days ago. I'm assuming it hasn't been fully fixed yet.

**Comment by posva** [comment] 2020-09-19 10:07
Vite needs to be released yet
