### ISSUE TITLE
Don't display files in public directory in minisearch

### ISSUE THREAD

**Issue by Pandapip1** [vuejs/vitepress#2655] opened 2023-07-19 20:22 UTC
### Is your feature request related to a problem? Please describe.

Not really, but there's a related issue: https://github.com/vuejs/vitepress/issues/2629

### Describe the solution you'd like

A configuration option to hide all files in the public directory from minisearch.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-07-19 20:35
Duplicate of #2344

**Closed by brc-dd** 2023-07-19 20:35 UTC

**Comment by Pandapip1** [comment] 2023-07-19 20:41
Not sure how I missed that. Sorry!
