### ISSUE TITLE
Support search functionality for private repos

### ISSUE THREAD

**Issue by fallemand** [vuejs/vitepress#1467] opened 2022-10-11 13:57 UTC
### Is your feature request related to a problem? Please describe.

We are moving to `vitepress` in many private repositories from my company.  
We see that only `agolia` is supported as a search method, which requires open-source projects only.  
We are trying to migrate everything to the Vite ecosystem but this is pushing us back.

### Describe the solution you'd like

Can we have something similar like `vuepress@1`?  
Thanks!

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-10-11 15:30
Duplicate of #670

**Closed by brc-dd** 2022-10-11 15:30 UTC
