### ISSUE TITLE
code-group does not work

### ISSUE THREAD

**Issue by fro9-dev** [vuejs/vitepress#1981] opened 2023-02-23 05:58 UTC
### Describe the bug

code-group is used, but it does not work

### Reproduction

I used **stackblitz**

https://stackblitz.com/edit/vite-r6wzwe?file=docs/example.md

### Expected behavior

Tabs should be switched.

### System Info

```shell
stackblitz online
```

### Additional context

![image](https://user-images.githubusercontent.com/80403482/220830969-56452b7d-93fb-430f-8527-9be2ab894fbe.png)

The ID is always created the same.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-02-23 06:09
Can you try with alpha-46 instead and see if it's working?

**Comment by fro9-dev** [comment] 2023-02-23 06:14
> 대신 alpha-46으로 시도하고 작동하는지 확인할 수 있습니까?

Converted [stackblitz] to [alpha-46] version.

The problem has not been resolved.

https://stackblitz.com/edit/vite-7komcv?file=docs/example.md

**Comment by fro9-dev** [comment] 2023-02-23 06:17
I didn't notice any issues with the functionality until about 26 hours ago.

The problem started about 22 hours ago.

**Comment by MarkusKeck** [comment] 2023-02-23 14:59
I also had this issue a while ago, but this only appeared when multiple files had the same title.
I will take a look at this.

**Comment by yyx990803** [comment] 2023-03-13 08:25
Dug a bit deeper and noticed this is because `nanoid`, which is used to generate unique IDs for code groups, somehow always returns the same string on StackBlitz... not sure why though, as I can't reproduce this alone: https://stackblitz.com/edit/node-gnnwyj?file=package.json,index.js

**Comment by yyx990803** [comment] 2023-03-15 00:33
Fixed now on StackBlitz.

**Closed by yyx990803** 2023-03-15 00:33 UTC
Labels: upstream

**Comment by fro9-dev** [comment] 2023-03-15 04:43
> 이제 StackBlitz에서 수정되었습니다.

Was this a problem with StackBlitz?

**Comment by brc-dd** [comment] 2023-03-15 04:46
> Was this a problem with StackBlitz?

@fro9-dev Yes. The reproduction you shared is now working.
