### ISSUE TITLE
Cannot display image that with blank space in image file name

### ISSUE THREAD

**Issue by arcqiufeng** [vuejs/vitepress#1537] opened 2022-10-26 09:27 UTC
### Describe the bug

if the image file name has a space. For example, image 01.png

```md
![img](./image 01.png)
```

cannot display in web page, which can be display in `typora` or `mpe for vscode`.

### Reproduction

As described.

### Expected behavior

Can work.

### System Info

```shell
vitepress 1.0 alpha22 windows 11 22H2
node.js latest.
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-10-26 09:33
Duplicate of #573

**Closed by brc-dd** 2022-10-26 09:33 UTC
Labels: bug: pending triage
