### ISSUE TITLE
Markdown [Text]({{link}}/test) , how to use variables at `link`

### ISSUE THREAD

**Issue by wgf4242** [vuejs/vitepress#2352] opened 2023-05-07 17:30 UTC
example 
```
<script setup>
import { ref } from 'vue'

const host = ref("http://test.com")
</script>

[Test]({{host}}/admin)
```
Got url like `%28%7b%7bhost%7d%7d%2fadmin`, not `http://test.com/admin`

**Comment by brc-dd** [comment] 2023-05-07 17:32
Duplicate of https://github.com/vuejs/vitepress/issues/2099#issuecomment-1481350268
Duplicate of #2240
Duplicate of #2304

**Closed by brc-dd** 2023-05-07 17:32 UTC
