### ISSUE TITLE
improve: missing `env` properties for Content Loader when `render` is specified

### ISSUE THREAD

**Issue by nekomeowww** [vuejs/vitepress#4349] opened 2024-11-10 06:03 UTC
## Summary

For general VitePress page renders, properties of `env` are available for `markdown-it` plugins to peek file path related info:

https://github.com/vuejs/vitepress/blob/36e0c1a3dbd3e5259fe08a480cc0ca3a1d48ba9b/src/node/markdownToVue.ts#L113-L122

However, for [content loader](https://vitepress.dev/guide/data-loading), if specified such 

```typescript
export default createContentLoader('/**/*.md', {
  render: true,
  transform() {
    return []
  },
})
```

content loader function, with our [Lazy loading blurred thumbnails | Nólëbase Integrations](https://nolebase-integrations.ayaka.io/pages/en/integrations/markdown-it-unlazy-img/) `markdown-it` plugin where `env.path` and  `env.relativePath` are required, since users are not allowed to toggle these unsupported `markdown-it` plugins for content loaders, they will not be able to use content loaders with `markdown-it-unlazy-img` together.

I found the code here, for content loaderss, within the `render` function, `env` properties are not injected as what VitePress's `render` would do:

https://github.com/vuejs/vitepress/blob/36e0c1a3dbd3e5259fe08a480cc0ca3a1d48ba9b/src/node/contentLoader.ts#L147

## Proposal

- Add `env` properties
- Allow users to reconfigure `md.use`

**Comment by brc-dd** [comment] 2024-11-10 08:22
Duplicate of #4331

**Closed by brc-dd** 2024-11-10 08:22 UTC
Labels: bug
