### ISSUE TITLE
How to click imageto enlarge the image ？

### ISSUE THREAD

**Issue by 810505339** [vuejs/vitepress#1882] opened 2023-02-02 03:20 UTC
### Describe the bug

How to click imageto enlarge the image ？

### Reproduction

How to click imageto enlarge the image ？

### Expected behavior

How to click imageto enlarge the image ？

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 Intel(R) Core(TM) i9-10900T CPU @ 1.90GHz
    Memory: 18.87 GB / 31.72 GB
  Binaries:
    Node: 14.19.0 - ~\AppData\Roaming\nvm\nodejs\node.EXE
    npm: 6.14.15 - ~\AppData\Roaming\nvm\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-alpha.45 => 1.0.0-alpha.45
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-02-02 07:37
Duplicate of #854

**Closed by brc-dd** 2023-02-02 07:37 UTC
Labels: bug: pending triage
