### ISSUE TITLE
base not used in route.path in server side

### ISSUE THREAD

**Issue by privatenumber** [vuejs/vitepress#587] opened 2022-03-22 19:32 UTC
### Describe the bug

When using [`base`](https://vitepress.vuejs.org/config/basics.html#base), `route.path` is different across client and server.

For example, when using base `/base/` and logging `route.path`, `vitepress build` will log `/index.html`, but when visited in the browser, it logs `/base/index.html`.

### Reproduction

[Minimal reproduction link](https://github.com/privatenumber/issue-reproductions/tree/master/reproductions/vuejs/vitepress/587)

1. Create a project with the following files:

.vitepress/config.js
```js
import { defineConfig } from 'vitepress'

export default defineConfig({
	base: '/base/'
})
```

index.md:
```html
<script setup>
import { useRoute } from 'vitepress';

const route = useRoute();
console.log(`\n\nBUG: "route.path" is different across server and client: "${route.path}"\n\n`);
</script>

Hello world
```

2. Run`vitepress build` and see `/index.html` get logged

3. Run `vitepress serve` and see `/base/index.html` get logged

### Expected behavior

For `route.path` to be consistent across server and client.

### System Info

```shell
N/A
```

### Additional context

Related: https://github.com/vuejs/vitepress/issues/446

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment] 2022-05-23 07:29
Duplicate of #446

**Closed by kiaking** 2022-05-23 07:29 UTC
Labels: bug: pending triage
