### ISSUE TITLE
Outline has badge text

### ISSUE THREAD

**Issue by ponjs** [vuejs/vitepress#1789] opened 2023-01-13 08:07 UTC
### Describe the bug

When the title has the badge, the generated catalog contains badge text (but not when you click on the anchor of the title).

### Reproduction

Docs:
``` md
## success <Badge type="danger" text="2.5.0" />
```
Preview:
![image](https://user-images.githubusercontent.com/39897744/212268865-6317d21d-c10c-4210-b037-530efaf9e94f.png)

### Expected behavior

When the title has the badge, the corresponding directory text should not have badge text.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 1.70 GB / 15.43 GB
Binaries:
    Node: 14.20.0 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - D:\nodejs\yarn.CMD
    npm: 6.14.17 - D:\nodejs\npm.CMD
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.19041.1566
npmPackages:
    vitepress: ^1.0.0-alpha.36 => 1.0.0-alpha.36
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-01-13 09:37
Duplicate of #1714

**Closed by brc-dd** 2023-01-13 09:37 UTC
Labels: bug: pending triage
