### ISSUE TITLE
TypeScript type-checking fails on `default-theme` components for missing internal declarations

### ISSUE THREAD

**Issue by Byloth** [vuejs/vitepress#3027] opened 2023-09-28 11:06 UTC
### Describe the bug

I'm using some VitePress default theme's components within my project.  
To do so, I defined an alias inside me `tsconfig.json` file as follow:
```ts
  "paths": {
    "@vitepress/theme/*": ["node_modules/vitepress/dist/client/theme-default/*"],
  }
```

In one case in particular, I'm using the `VPLink` component, so I import it as follow:
```ts
import VPLink from "@vitepress/theme/components/VPLink.vue";
```

---

Everything worked fine and I was happy about it...  
Until today, when I updated my dependencies and -of course- VitePress from version `1.0.0-beta.7` to version `1.0.0-rc.20`.

Now, when I run `vue-tsc --noEmit` it throws me the following error:

```
node_modules/vitepress/dist/client/theme-default/components/VPLink.vue:3:31 - error TS7016: Could not find a declaration file for module '../support/utils'. '/home/matteo/byloth/vuert/node_modules/vitepress/dist/client/theme-default/support/utils.js' implicitly has an 'any' type.

3 import { normalizeLink } from '../support/utils'
                                ~~~~~~~~~~~~~~~~~~

node_modules/vitepress/dist/client/theme-default/components/VPLink.vue:4:33 - error TS7016: Could not find a declaration file for module '../../shared'. '/home/matteo/byloth/vuert/node_modules/vitepress/dist/client/shared.js' implicitly has an 'any' type.

4 import { EXTERNAL_URL_RE } from '../../shared'
                                  ~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/vitepress/dist/client/theme-default/components/VPLink.vue:3
```

### Reproduction

Here's the project where it happens: https://github.com/Byloth/vuert

To reproduce, simply run:
```sh
yarn install
yarn check:types
```

### Expected behavior

It should not throw any error.

### System Info

```Text
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-13620H
    Memory: 2.14 GB / 7.57 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.1.0 - /usr/bin/npm
    pnpm: 8.6.9 - /usr/bin/pnpm
  npmPackages:
    vitepress: ^1.0.0-rc.20 => 1.0.0-rc.20
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-10-19 15:03
duplicate of #2595

**Closed by brc-dd** 2023-10-19 15:03 UTC
Labels: bug: pending triage
