### ISSUE TITLE
`ERR_REQUIRE_ESM` error when build with esm module.

### ISSUE THREAD

**Issue by dewfall123** [vuejs/vitepress#601] opened 2022-04-12 16:01 UTC
### Describe the bug

import a esm module, and run `docs:build`
```
✖ rendering pages...
build error:
 Error [ERR_REQUIRE_ESM]: require() of ES Module...
```

### Reproduction

https://github.com/dewfall123/vitepress-issues-2.git

run command `yarn docs:build`

### Expected behavior

no error.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 6.34 GB / 15.93 GB
  Binaries:
    Node: 16.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 100.0.4896.75
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.39)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: ^0.22.3 => 0.22.3
```

### Additional context

same as #592

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by yl-199807** [comment] 2022-05-22 12:41
same，have you solved it?

**Comment by brc-dd** [comment] 2022-05-28 18:15
Duplicate of #476

**Closed** 2022-05-29 10:16 UTC
Labels: duplicate
