### ISSUE TITLE
配置nav的时候 支持children选项 可以方便进行nav的分组

### ISSUE THREAD

**Issue by LiCHUYA** [vuejs/vitepress#3983] opened 2024-06-24 05:08 UTC
### Is your feature request related to a problem? Please describe.

在类似于下拉菜单分组的时候,往往会出现items嵌套层级比较深,不好进一步扩展维护
![image](https://github.com/vuejs/vitepress/assets/116934223/d635a7a1-8e69-4f24-8d51-f1e3a34e124d)

### Describe the solution you'd like

我已经写好了demo,并且在vitepress源码中已经更改,但本人由于第一次pr,不太会使用,在这附上一些代码片段,以及使用示例。
`import type { DefaultTheme } from 'vitepress'
const handleData = [
  {
    id: 0,
    text: '学习心得1',
    children: [
      {
        groupId: '0-0',
        text: '学习心得2',
        link: 'xxx',
      },
      {
        groupId: '0-0',
        text: '学习心得3',
        link: 'xxx',
      },
      {
        groupId: '0-1',
        text: '学习心得4',
        link: 'xxx',
      },
      {
        groupId: '0-2',
        text: '学习心得5',
        link: 'xxx',
      },
      {
        groupId: '0-3',
        text: '学习心得6',
        link: 'xxx',
      },
    ],
  },
  {
    id: 1,
    text: '学习心得1',
    children: [
      {
        groupId: '1-1',
        text: '学习心得2',
        link: 'xxx',
      },
      {
        groupId: '1-2',
        text: '学习心得3',
        link: 'xxx',
      },
      {
        groupId: '1-3',
        text: '学习心得4',
        link: 'xxx',
      },
    ],
  },
]

function transformHandleDataToNav(handleData) {
  return handleData.map((dataItem) => {
    // 创建顶级nav项
    const navItem = { text: dataItem.text, items: [] }

    // 如果有子项，根据groupId进行分组
    if (dataItem.children) {
      const groups = new Map()

      dataItem.children.forEach((child) => {
        const groupId = child.groupId.split('-')[1] // 假设groupId格式为"id-index"
        if (!groups.has(groupId)) {
          groups.set(groupId, [])
        }
        groups.get(groupId).push({ text: child.text, link: child.link })
      })

      // 将分组转换为items数组
      groups.forEach((groupItems) => {
        navItem.items.push({ items: groupItems })
      })
    } else if (dataItem.link) {
      // 如果没有子项但有链接，直接设置链接
      navItem.link = dataItem.link
    }

    return navItem
  })
}

const nav1 = transformHandleDataToNav(handleData)
console.log(nav1)

export const nav: DefaultTheme.Config['nav'] = nav1
`,在这个示例中,我们可以清晰的配置navGroup选项,只需要在groupid去配置,以"id-index"手动式声明,当然也可以在runtime时编译
添加id之类的。

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by LiCHUYA** [comment] 2024-06-24 05:09
import type { DefaultTheme } from 'vitepress'
const handleData = [
  {
    id: 0,
    text: '学习心得1',
    children: [
      {
        groupId: '0-0',
        text: '学习心得2',
        link: 'xxx',
      },
      {
        groupId: '0-0',
        text: '学习心得3',
        link: 'xxx',
      },
      {
        groupId: '0-1',
        text: '学习心得4',
        link: 'xxx',
      },
      {
        groupId: '0-2',
        text: '学习心得5',
        link: 'xxx',
      },
      {
        groupId: '0-3',
        text: '学习心得6',
        link: 'xxx',
      },
    ],
  },
  {
    id: 1,
    text: '学习心得1',
    children: [
      {
        groupId: '1-1',
        text: '学习心得2',
        link: 'xxx',
      },
      {
        groupId: '1-2',
        text: '学习心得3',
        link: 'xxx',
      },
      {
        groupId: '1-3',
        text: '学习心得4',
        link: 'xxx',
      },
    ],
  },
]

function transformHandleDataToNav(handleData) {
  return handleData.map((dataItem) => {
    // 创建顶级nav项
    const navItem = { text: dataItem.text, items: [] }

    // 如果有子项，根据groupId进行分组
    if (dataItem.children) {
      const groups = new Map()

      dataItem.children.forEach((child) => {
        const groupId = child.groupId.split('-')[1] // 假设groupId格式为"id-index"
        if (!groups.has(groupId)) {
          groups.set(groupId, [])
        }
        groups.get(groupId).push({ text: child.text, link: child.link })
      })

      // 将分组转换为items数组
      groups.forEach((groupItems) => {
        navItem.items.push({ items: groupItems })
      })
    } else if (dataItem.link) {
      // 如果没有子项但有链接，直接设置链接
      navItem.link = dataItem.link
    }

    return navItem
  })
}

const nav1 = transformHandleDataToNav(handleData)
console.log(nav1)

export const nav: DefaultTheme.Config['nav'] = nav1

**Comment by LiCHUYA** [comment] 2024-06-24 05:10
![code-snapshot-1719205808373](https://github.com/vuejs/vitepress/assets/116934223/fd155abe-7687-4301-b3dc-661fe0987cf6)

**Comment by 11-shou** [comment] 2024-06-27 06:55
我也这么希望，兄嘚

**Comment by brc-dd** [comment] 2024-06-27 07:03
Duplicate of #3816

**Closed by brc-dd** 2024-06-27 07:03 UTC

**Comment by Zhengqbbb** [comment] 2024-06-27 07:21
在开发完成前，如果定义需求可以这样玩：
https://vitepress.dev/guide/extending-default-theme#overriding-internal-components
