### ISSUE TITLE
Project not working

### ISSUE THREAD

**Issue by QiYoe** [vuejs/vitepress#357] opened 2021-08-10 09:16 UTC
### Describe the bug

vitepress dependency error

### Reproduction

Errors reported during project startup and packaging

### Expected behavior

project can start and package normally

### System Info

```shell
Error: 'defineEmit' is not exported by node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js, imported by node_modules/vitepress/dist/client/theme-default/components/NavBar.vue?vue&type=script&setup=true&lang.ts
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by posva** [comment] 2021-08-10 09:38
Duplicate of #355

**Closed by posva** 2021-08-10 09:38 UTC
Labels: bug: pending triage
