### ISSUE TITLE
Automatic Headings in Sidebar

### ISSUE THREAD

**Issue by Taialt97** [vuejs/vitepress#3755] opened 2024-04-05 11:31 UTC
### Describe the bug

Setting 'auto' to a sidebar property in config.js does not create automatic sidebar elements.

### Reproduction

```
        sidebar: {
            '/projects/': 'auto',
        }
```

### Expected behavior

 A sidebar should be auto generated using the headings provided in the markdown files for the projects page

### System Info

```Text
vitepress version: 1.0.2
vite version: 1.0.0
Node version: v21.6.1
OS version: Windows 11 Pro 23H2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-04-12 06:40
Duplicate of #1297

Use the plugins mentioned there instead.

**Closed by brc-dd** 2024-04-12 06:40 UTC
