### ISSUE TITLE
静态资源解析打包的时候报错

### ISSUE THREAD

**Issue by jaycethanks** [vuejs/vitepress#3295] opened 2023-12-06 07:02 UTC
### Describe the bug

像 下面这样的资源路径在打包的时候报错 “Error: [vite]: Rollup failed to resolve import "09_Java 语法.assets/image-20210630002730821.png" from "/home/jayce/workspace_personal/learn-content/contents/java-kuangshen_learn/09_Java 语法.md".”
```
 ![image-20210630003516350](09_Java 语法.assets/image-20210630003516350.png)
```
必须换成 
```
[image-20210630003516350](./09_Java 语法.assets/image-20210630003516350.png)
```

太多了换起来好麻烦

### Reproduction

- 

### Expected behavior

希望能支持像 `[image-20210630003516350](09_Java 语法.assets/image-20210630003516350.png)` 这种资源引入方式，  或者支持正则配置

### System Info

```Text
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 13.57 GB / 15.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.7.1 - /usr/local/bin/pnpm
  npmPackages:
    vitepress: 1.0.0-rc.31 => 1.0.0-rc.31
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Aurorxa** [comment] 2023-12-20 04:25
* 这个你自己处理下啊，这是 Node.js 的规则，和 vitepress 无关，并且路径不要用中文。
* 如果你用的是 Typora ，那么可以这么设置：
![image](https://github.com/vuejs/vitepress/assets/25677587/d3751a87-0553-4c72-a1a0-b46958b0a33e)
* 这样，你可以截图的时候，直接在 markdown 文档里面复制即可，会自动帮你粘贴到对应的目录中。

**Comment by Octobug** [comment] 2024-01-08 14:36
Cannot reproduce this on macOS.

On macOS, `![Image](09_Java 语法.assets/image-20210630003516350.png)` won't be parsed as an image for there is a ` ` (blank space).

But `![Image](09_Java%20语法.assets/image-20210630003516350.png)` and `![Image](./09_Java%20语法.assets/image-20210630003516350.png)` both work fine.

**Comment by brc-dd** [comment] 2024-01-08 14:51
> won't be parsed as an image for there is a blank space

Yeah, that's compliant with commonmark spec. You can either manually percent encode it (to `%20`) or use angular brackets - `![image-20210630003516350](<09_Java 语法.assets/image-20210630003516350.png>)` - Both seem to be working fine for me.

**Comment by yangdong520** [comment] 2024-04-10 21:54
自己整个图床，不好么

**Comment by Aurorxa** [comment] 2024-04-10 22:27
@yangdong520 可能觉得图床会宕机吧

**Comment by yangdong520** [comment] 2024-04-12 01:52
> @yangdong520 可能觉得图床会宕机吧

不能这么想，那放在本地，磁盘还会损坏呢，能工提升自己生产力的东西，能用坚决用，省下来时间不是又可以多敲几行代码了么

**Comment by awxiaoxian2020** [comment] 2024-04-12 11:23
Off topic, closing for now.

**Closed by awxiaoxian2020** 2024-04-12 11:23 UTC
Labels: need more info
