### ISSUE TITLE
Occured 404 in some pages

### ISSUE THREAD

**Issue by kazupon** [vuejs/vitepress#885] opened 2022-07-01 01:57 UTC
### Describe the bug

I'm migrate vue-i18n docs site with vitepress v1 alpha.4
The config.ts for that docs consists of Mulutiple Sidbars.
Config.ts is here:
https://github.com/intlify/vue-i18n-next/blob/docs/vitepress1/docs/.vitepress/config.ts

`/guide/` sidebar has items, but it’s wried, we will access the `Message Format Syntax` and `Fallbacking` items resulting in a 404.

These settings are here.
- `Message Format Syntax`: https://github.com/intlify/vue-i18n-next/blob/e59dcca32e1aa6af966651f02bb624081299c2bf/docs/.vitepress/config.ts#L114-L117
- `Fallbacking`:  https://github.com/intlify/vue-i18n-next/blob/e59dcca32e1aa6af966651f02bb624081299c2bf/docs/.vitepress/config.ts#L134-L137

The previous version of vitepress worked, so here is the site URL and config for your reference.

- URL: https://vue-i18n.intlify.dev/
- config: https://github.com/intlify/vue-i18n-next/blob/master/docs/.vitepress/config.js

### Reproduction

Repository:  https://github.com/intlify/vue-i18n-next

Reproduction step:
1. `git clone git@github.com:intlify/vue-i18n-next.git`
2. `git checkout docs/vitepress1`
3. `pnpm install`
4. `pnpm docs:setup`
5. `pnpm docs:dev`
6. go to http://localhost:3000/
7. go to Guid via navigation `Guide` menu
8. go to  [Message Format Syntax](http://localhost:3000/guide/essentials/syntax.html) via sidebar
9. go to  [Fallbacking](http://localhost:3000/guide/essentials/fallback.html) via sidebar 

### Expected behavior

I hope that 404 won't occur on these pages

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 9.93 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/bin/.nvm/versions/node/v18.4.0/bin/node
    npm: 8.12.1 - ~/bin/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 97.0.1
    Safari: 15.5
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-07-01 04:59
Hi! This is duplicate of #419. Your `fallback.md` has `process.env.NODE_ENV !== 'production'` at line 62.

**Closed by brc-dd** 2022-07-01 04:59 UTC
Labels: bug: pending triage
