### ISSUE TITLE
Escaping curly braces

### ISSUE THREAD

**Issue by bojanrajh** [vuejs/vitepress#1836] opened 2023-01-23 16:35 UTC
### Describe the bug

It is impossible to render `{{ foo }}` or `{{ bar() }}`:
 - `[Vue warn]: Property "foo" was accessed during render but is not defined on instance.`
 - `Uncaught (in promise) TypeError: \_ctx.bar is not a function`

### Reproduction

See [Variables](https://stackblitz.com/edit/vite-qf1xbf?file=docs%2Fexample.md) and [Functions](https://stackblitz.com/edit/vite-qf1xbf?file=docs%2Fexample2.md) examples on [Stackblitz](https://stackblitz.com/edit/vite-qf1xbf?file=docs%2Findex.md)

### Expected behavior

It should work as standard Markdown syntax - `{{ foo }}` and `{{ bar() }}`

### System Info

```shell
See Stackblitz examples #1 (Variables) and #2 (Functions).
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-01-23 16:38
Duplicate of https://github.com/vuejs/vitepress/discussions/480

**Closed by brc-dd** 2023-01-23 16:38 UTC
Labels: bug: pending triage
