### ISSUE TITLE
markdown parse bug

### ISSUE THREAD

**Issue by webpon** [vuejs/vitepress#1818] opened 2023-01-20 08:48 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/50807258/213653573-8c91c323-716d-4850-9768-e9cdf12e6220.png)
![image](https://user-images.githubusercontent.com/50807258/213653640-ddf7de2b-8255-4550-b771-7c96bbf875b0.png)

### Reproduction

1

### Expected behavior

1

### System Info

```shell
1
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-01-20 09:01
Duplicate of https://github.com/vuejs/vitepress/discussions/480

**Closed by brc-dd** 2023-01-20 09:01 UTC
Labels: bug: pending triage

**Comment by webpon** [comment] 2023-01-20 17:03
thank you

**Comment by webpon** [comment] 2023-01-20 17:04
> Duplicate of #480

thank you
