### ISSUE TITLE
Dev mode throws lifecycle warning for xstate/vue (probably other composables?)

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vitepress#243] opened 2021-02-18 15:59 UTC
**Describe the bug**
When using `@state/vue`, which is a composition function to use xstate in Vue components. VitePress in dev mode (**and only in dev mode**) will throw `onMounted` and `onUnmounted` lifecycle warnings and prevent the library from working.

Everything works fine in build/serve mode, so I suspect something about the dev-serve config is acting up.

**To Reproduce**
https://github.com/TheDutchCoder/vitepress-xstate-reproduction

**Expected behavior**
No warnings to be thrown in dev mode, and have the library function (it's not reactive right now in dev mode)

**System Info**
- vitepress version: 0.12.2
- vite version: whatever ships with vitepress
- Node version: 12.19.0
- OS version: 11.2.1

**Comment by TheDutchCoder** [comment] 2021-02-24 13:53
Okay Here's the reproduction: https://github.com/TheDutchCoder/vitepress-xstate-reproduction

## Steps
1. Clone repo
2. `npm i`
2. `npm run docs:dev`
3. See the warnings in the console and clicking the button won't do anything
4. `npm run docs:build && npm run docs:serve`
5. No warnings in the console and the button works fine

**Comment by ErikCH** [comment] 2021-03-24 20:42
I'm getting the same issue with the lastest version of Vitepress. It seems to happen on Vuepress too, only in dev mode. Makes testing with XState very difficult.

**Comment by LinusBorg** [comment] 2021-03-24 22:10
* `@xstate/vue` only provides a UMD build, no *esm* build
* Vite has to convert this module into an ES module.
* In that process, it bundles the `vue` / `@vue/runtime-core` / `@vue/runtime-dom` packages *into* that optimized version of `@xstate/vue` (you can have a look at `node_modules/.vite/@xstate_vue.js`)
* Now you have two copies of Vue in the app, which leads to this error.

The cleanest solution would be to have `@xstate/vue` provide an esm build to support modern JS bundlers/environments.

Short of that, Vite might be able to skip the vue packages in that optimization process, maybe? Though it feels not right to kind of hardcode such an exception, But maybe it's more a bug in Vite to bundle Vue into this as it's an esm build already?

I don't think Vuepress can solve that, really.

**Comment by patak-js** [comment] 2021-03-25 20:29
We were talking in Vite Land with @LinusBorg, including a `vite.config.js` file in the root of https://github.com/TheDutchCoder/vitepress-xstate-reproduction, fixed `docs:dev` and `docs:build` for me:
```js
export default {
  resolve: { 
    dedupe: ['vue'] 
  }
}
```
I don't know if this is just hiding another issue that could be fixed in `@xstate/vue`

**Comment by LinusBorg** [comment] 2021-03-25 20:32
Nah, I don't think @xstate/vue can do anything else. They also do provide an esm build, I just missed it as it's not done with theirnrollup build, but directly with `tsc.

Their setup seems fine.

@patak-js maybe we should rather consider adding the define option for vue as a default in the vue template. 

Duplicates of Vue always create problems and can happen in a number of different contexts.

**Comment by patak-js** [comment] 2021-03-25 20:33
I think I misread the original issue, I had a fail in dev and I thought dedupe was fixing that. But I see that the button is still not working during dev.

**Comment by patak-js** [comment] 2021-03-25 21:51
For what is worth, looks like it is an issue with VitePress. The same component using `@xstate/vue` works fine with the latest vite on a fresh create-app app.
I also tried to update Vite and Vue to their latest versions for VitePress and yarn link locally, but the reproduction stills failed.

**Comment by Andarist** [comment] 2021-03-25 22:09
Yep - the provided repro is using `@xstate/vue@0.4.0` so you might want to upgrade to `@xstate/vue@0.5.0`. But even after upgrading, I don't see a reason why the Vue would be bundled together with it as it's an external dependency (a peer) and all. 

It seems to me that it's an issue with the tooling.

**Comment by santicros** [comment] 2021-03-25 22:51
Also as a reminder xstate/vue@0.4.0 and up need Vue 3, so it's possible that it doesn't work with Vuepress as @ErikCH was saying. But should work properly with Vitepress as it does with Vite and Vue 3.

**Comment by kiaking** [comment] 2022-05-24 01:23
Is this still an issue 👀 ?

**Closed** 2022-06-01 04:25 UTC
Labels: need more info
