### ISSUE TITLE
This is a suggestion

### ISSUE THREAD

**Issue by trry-github** [vuejs/vitepress#434] opened 2021-10-31 05:45 UTC
### Is your feature request related to a problem? Please describe.

When I use Element-Plus in VitePress, the partial style of the component is modified. The reason is VitePress  `src/client/theme-default/styles/layout.css`  File reset all styles.

![image](https://user-images.githubusercontent.com/67309192/139569810-acbaeab7-3e02-455d-aea0-d28c3be19769.png)

![image](https://user-images.githubusercontent.com/67309192/139569822-fa5c9a70-43bd-4ca7-8a88-4c32cce21083.png)

### Describe the solution you'd like

I hope this code only takes effect in VitePress.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by trry-github** [comment] 2021-11-04 10:01
@kiaking

**Comment by brc-dd** [comment] 2022-01-13 04:44
The order of style imports matter. Try doing it like this:

```ts
// .vitepress/theme/index.ts
import DefaultTheme from 'vitepress/theme';
import 'element-plus/dist/index.css';

// ...
```

**Comment by kiaking** [comment] 2022-05-23 07:09
Duplicate of https://github.com/vuejs/vitepress/issues/199

**Closed by kiaking** 2022-05-23 07:09 UTC
