### ISSUE TITLE
我配置了markdown主题，但是永远是dark模式，light无效

### ISSUE THREAD

**Issue by didoee** [vuejs/vitepress#1312] opened 2022-09-09 10:36 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/112919246/189330923-dd69c9cf-6995-4362-947d-03468547e980.png)

### Reproduction

`markdown: {
		theme: {
			light: 'github-light',
			dark: 'github-dark',
		}
	},`

### Expected behavior

能够使用light模式

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.41 GB / 15.86 GB
  Binaries:
    Node: 16.17.0 - D:\software\nodejs\node.EXE
    Yarn: 1.22.19 - D:\software\nodejs\node_global\yarn.CMD
    npm: 8.18.0 - D:\software\nodejs\node_global\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vitepress: 1.0.0-alpha.13 => 1.0.0-alpha.13
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ylw5** [comment] 2022-09-09 11:06
我也是这样配置，结果是同一个代码块重复两次，一次是dark，一次是light

**Comment by brc-dd** [comment] 2022-09-09 12:34
duplicate of #1245

**Closed by brc-dd** 2022-09-09 12:34 UTC
Labels: bug: pending triage
