### ISSUE TITLE
If I use the canonicalUrl example syntax in vitepress version 1.2.2, an error occurs when building.

### ISSUE THREAD

**Issue by isishome** [vuejs/vitepress#3923] opened 2024-05-27 15:49 UTC
### Describe the bug

If I use the canonicalUrl example syntax in vitepress version 1.2.2, an error occurs when building.

str.replace is not a function

So, I downgraded to version 1.2.1 and the error did not occur.

### Reproduction

install Vitepress v 1.2.2

canonicalUrl example [canonical ex](https://vitepress.dev/reference/site-config#example-adding-a-canonical-url-link)

```Text
const canonicalUrl = `https://myhome.com/${pageData.relativePath}`.replace(/index\.md$/, '').replace(/\.(md|html)$/, '')
pageData.frontmatter.head ??= []
pageData.frontmatter.head.push(['meta', { property: 'og:title', content: pageData.title }])
pageData.frontmatter.head.push(['meta', { property: 'og:description', content: pageData.description }])
pageData.frontmatter.head.push(['meta', { property: 'og:image', content: 'https://myhome.com/images/og.jpg' }])
pageData.frontmatter.head.push(['meta', { property: 'og:url', content: canonicalUrl }])
pageData.frontmatter.head.push(['link', { rel: 'canonical', href: canonicalUrl }])
```

npm run docs:build

### Expected behavior

failed to build

occur error => str.replace is not a function

### System Info

```Text
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 21.07 GB / 31.92 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (124.0.2478.97)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    vitepress: ^1.2.2 => 1.2.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-05-27 16:01
Please share a reproducible example. Most likely your canonicalUrl variable is undefined in some case. Try wrapping the head.push statement inside a condtion.

**Comment by isishome** [comment] 2024-05-27 16:23
> Reproduction

The reproduction has been corrected.

Versions prior to v 1.2.2 build with the same code without issue.

**Comment by brc-dd** [comment] 2024-05-27 16:42
It still is not reproducible.

<img width="614" alt="image" src="https://github.com/vuejs/vitepress/assets/40380293/2b9812d0-c8df-4b1c-bcd6-afead0caf603">

\
Please share an example using https://vitepress.new

**Comment by isishome** [comment] 2024-05-28 03:08
> It still is not reproducible.
> 
> <img alt="image" width="614" src="https://private-user-images.githubusercontent.com/40380293/334169284-2b9812d0-c8df-4b1c-bcd6-afead0caf603.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjU3NjMsIm5iZiI6MTcxNjg2NTQ2MywicGF0aCI6Ii80MDM4MDI5My8zMzQxNjkyODQtMmI5ODEyZDAtYzhkZi00YjFjLWJjZDYtYWZlYWQwY2FmNjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAzMDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YzNhODMyZGYwMTZmZTJjMjA5Yzc1Yzk5NmEzZDQzYmM0Nzc4ZWQ5OTQyNjQ0NDBjYmIzZjgzMjg3ODRhNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nR9pap_ts-aCM9xfmYdsDP_SxfNx-aXEh0h_exnCzPU">
> Please share an example using https://vitepress.new
> 
> Like I said, you might have some attribute value that is not a string.

If I run it in developer mode, there is no problem, but if I just run the build, the following error occurs.

If you comment out the canonical syntax, it builds without a problem.

`
str.replace is not a function
TypeError: str.replace is not a function
    at escapeHtml$1 (file:///D:/Projects/myhome/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:19945:14)
    at file:///D:/Projects/myhome/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46689:24
    at Array.map (<anonymous>)
    at renderAttrs (file:///D:/Projects/myhome/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46687:29)
    at file:///D:/Projects/myhome/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46671:33
    at Array.map (<anonymous>)
    at renderHead (file:///D:/Projects/myhome/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46670:10)
    at renderPage (file:///D:/Projects/myhome/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46625:13)
    at async pMap.concurrency (file:///D:/Projects/myhome/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46770:11)
    at async file:///D:/Projects/myhome/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:2618:20
`

**Comment by isishome** [comment] 2024-05-28 03:14
I just found the cause, and found that the replace used in the canonicalUrl variable is not the cause, but occurs in pageData.description.

**Comment by brc-dd** [comment] 2024-05-28 12:01
Previous escape function was more lax and incorrectly serialised such values. pageData.description should always be a string unless you’ve wrong frontmatter. Most likely it wouldn’t have worked correctly with older versions too. Sure they won’t throw error, but the generated html tags will be wrong. Closing as it’s not a bug with VitePress rather wrong content.

**Closed by brc-dd** 2024-05-28 12:01 UTC
Labels: need more info
