### ISSUE TITLE
 create a sidebar automatically from filesystem structure

### ISSUE THREAD

**Issue by YQisme** [vuejs/vitepress#2327] opened 2023-05-01 12:48 UTC
### Is your feature request related to a problem? Please describe.

Create a sidebar automatically from the filesystem structure: each folder creates a sidebar category, and each file creates a doc link.

### Describe the solution you'd like

https://docusaurus.io/docs/sidebar/autogenerated.
Docusaurus has this feature and it's very usefuf.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-05-01 13:06
Duplicate of #1297

**Closed by brc-dd** 2023-05-01 13:06 UTC

**Comment by boozedog** [comment] 2023-05-03 00:13
@YQisme I am trying out this plugin to accomplish what you're asking and so far it is working well. https://github.com/jooy2/vitepress-sidebar

Hope that helps

**Comment by QC2168** [comment] 2023-05-05 03:59
@YQisme  Hello，you can use[vite-plugin-vitepress-auto-sidebar](https://github.com/QC2168/vite-plugin-vitepress-auto-sidebar)，It can help you automatically create sidebar data and insert it into the configuration file
