### ISSUE TITLE
[Navigate] backward and forward buttons do not work as expected

### ISSUE THREAD

**Issue by stygian-desolator** [vuejs/vitepress#972] opened 2022-07-13 01:23 UTC
### Describe the bug

The back and forward buttons do not work when I click on the menu to navigate to a different page.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/73412177/178627332-bbed9e1c-a4b6-41c4-9fa0-0d5af671b67d.png">

### Reproduction

https://vitepress.vuejs.org/guide/getting-started.html

### Expected behavior

The back and forward buttons work as expected

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 71.08 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Chrome Canary: 105.0.5176.0
    Firefox: 101.0.1
    Safari: 15.3
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-07-13 07:10
> The back and forward buttons do not work when I click on the menu to navigate to a different page.

Can you explain a bit more? They appear to be working fine for me:

https://user-images.githubusercontent.com/40380293/178672782-91f9a562-292b-4f3b-96d6-8a385a451ad4.mp4

**Comment by stygian-desolator** [comment] 2022-07-13 12:26
That's weird, it's not normal on my Chrome.

https://user-images.githubusercontent.com/73412177/178732802-0c1a0dad-f38f-4ece-82dd-aa2834b1e319.mov

**Comment by brc-dd** [comment] 2022-07-13 17:39
I am still not able to reproduce this, but it maybe due to some race condition, or maybe something else. Marked this as a bug (needs investigation). Anyway, your PR doesn't seem like a proper fix. `replaceState` must be called before `pushState` otherwise the scroll position won't be preserved. I am closing that for now.

**Comment by yyx990803** [comment] 2023-03-13 08:06
Closing as non-reproducible

**Closed by yyx990803** 2023-03-13 08:06 UTC
Labels: bug
