### ISSUE TITLE
Build operation cannot handle encoded image URL characters 

### ISSUE THREAD

**Issue by justinaskav** [vuejs/vitepress#2278] opened 2023-04-23 14:10 UTC
### Describe the bug

The same as #220, it wasn't solved

> In the markdown file, When reference a image file with encoded URL, it works in the dev mode, but it would fail to build.

### Reproduction

1. Create an image with name, e.g. `A B.jpeg`
2. Add image to markdown file, like this: `![](./A%20B.jpeg)`
3. run `npm run docs:dev` to make sure that URL is correct
4. run `npm run docs:build`

Example: https://stackblitz.com/edit/vite-zztdyw?file=docs/index.md

### Expected behavior

Should build successfully

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 102.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    npm: 9.6.4 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 16.3
  npmPackages:
    vitepress: ^1.0.0-alpha.73 => 1.0.0-alpha.73
```

### Additional context

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/23059846/233844276-91ac01cd-7e46-48c3-8fc8-e4e90bc5ed4b.png">

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by zonemeen** [comment] 2023-04-28 08:52
Duplicate of https://github.com/vuejs/vitepress/issues/573

**Closed** 2023-04-28 09:41 UTC
Labels: bug: pending triage
