### ISSUE TITLE
Code block title without code group

### ISSUE THREAD

**Issue by Lombra** [vuejs/vitepress#4027] opened 2024-07-08 12:58 UTC
### Is your feature request related to a problem? Please describe.

Code block title requires a code group. I like to put for example a file name as the title.

### Describe the solution you'd like

Allow specifying titles for code blocks outside of code groups, using the existing syntax.

ˋˋˋjs [main.js]
console.log("Hello World")
ˋˋˋ

(do code blocks not work here?)

### Additional context

I saw support for single code block titles being mentioned in the comments of an old issue discussing the implementation of the feature for code groups, but as far as I can tell, it never made it.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-07-08 13:00
Duplicate of #3746

**Closed by brc-dd** 2024-07-08 13:00 UTC

**Comment by brc-dd** [comment] 2024-07-08 13:02
> (do code blocks not work here?)

they work, but your nesting was wrong

````md
ˋˋˋjs [main.js]
console.log("Hello World")
```
````
