### ISSUE TITLE
[✨Feature Request]: Built-in `Annoucement Bar` support

### ISSUE THREAD

**Issue by xsjcTony** [vuejs/vitepress#4244] opened 2024-10-02 02:26 UTC
### Is your feature request related to a problem? Please describe.

Currently, it's a bit hard to hack into VitePress's default theme to make the announcement bar work.
I've had an implementation that extends the default theme but it still has some limitations.
- The navbar is using `fixed` position, so I have to deal with the gap manually, and it's really hard to do so when we can't really deal with the padding / margin top in case the announcement bar cross multiple lines, since the height is dynamic. Some JS is required.
- But if Vitepress can built it in, it's going to be easier since the layout can be changed to suit the built-in announcement bar, which is much better than a plugin-like thing.

### Describe the solution you'd like

The APIs and CSS in Docusaurus look just awesome.
API: https://docusaurus.io/docs/api/themes/configuration#announcement-bar
Implementation: [facebook/docusaurus/packages/docusaurus-theme-classic/src/theme/AnnouncementBar/index.tsx](https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/AnnouncementBar/index.tsx)

### Additional context

Would like it to be something like this:
![image](https://github.com/user-attachments/assets/4f76a220-48dd-4d55-9d6b-4da1bd0474ea)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-10-02 16:08
Duplicate of #2071

**Closed by brc-dd** 2024-10-02 16:08 UTC
