### ISSUE TITLE
Configuring the base as a CDN address will cause a hyperlink href exception

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vitepress#3132] opened 2023-10-24 02:13 UTC
### Describe the bug

Configuring the base as a CDN address will cause a hyperlink href exception
```html
<a  class="title"
  href="http:/abc.cdn.cn/hello/"
  data-v-b817187b>
  <!--[--><!--]--><!----><!--[-->VitePress<!--]--><!--[--><!--]-->
</a>
```

### Reproduction

// config.js
```javascript
export default ({
    base: 'http://abc.cdn.cn/hello/',
});
```

// index.md
```
# hello
![](world.png)
```

// dist/index.html
```html
...
<header class="VPNav" data-v-30b21250 data-v-04c31db4>
          <div class="VPNavBar" data-v-04c31db4 data-v-d8c1e712>
            <div class="container" data-v-d8c1e712>
              <div class="title" data-v-d8c1e712>
                <div class="VPNavBarTitle" data-v-d8c1e712 data-v-b817187b>
                  <a
                    class="title"
                    href="http:/abc.cdn.cn/hello/"
                    data-v-b817187b
                    ><!--[--><!--]--><!----><!--[-->VitePress<!--]--><!--[--><!--]--></a
                  >
                </div>
              </div>
...
```

### Expected behavior

href="/"
or
href="http://abc.cdn.cn/hello/"

### System Info

```Text
win11
chrome118
"vitepress": "1.0.0-rc.23"
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

Please review the following demo：
https://stackblitz.com/edit/github-tyb3oh-fjwkma?file=docs%2F.vitepress%2Fdist%2Findex.html
or
https://github.com/yangdan8/vitepress-bug.git

**Comment by brc-dd** [comment] 2023-10-24 03:51
It's not supported right now.

Duplicate of #736

#2467 will fix this, but it will need major rebase.

**Closed by brc-dd** 2023-10-24 03:51 UTC
Labels: bug: pending triage
