### ISSUE TITLE
Import code snippet inside a code block

### ISSUE THREAD

**Issue by JesusTheHun** [vuejs/vitepress#3875] opened 2024-05-08 19:45 UTC
### Is your feature request related to a problem? Please describe.

When presenting a function's signature, it can be valuable to share the type of the parameters in case of large types.
Using `twoslash` can do the trick with medium-sized types, but an object with 20+ properties will be eluded with `14 more`.

### Describe the solution you'd like

Support the syntax `<<< @/filepath` inside a code block.

### Describe alternatives you've considered

Right now you can import a code snippet, but only outside a code block. This means there will be two blocks, and `twoslash` won't be enabled on the imported code block.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-05-08 19:59
it is supported

**Comment by brc-dd** [comment] 2024-05-08 20:00
duplicate of #3823

**Closed by brc-dd** 2024-05-08 20:00 UTC
