### ISSUE TITLE
[Vue warn]: Property "include" was accessed during render but is not defined on instance. 

### ISSUE THREAD

**Issue by nbro** [vuejs/vitepress#3889] opened 2024-05-14 02:36 UTC
### Describe the bug

I have a markdown file with the following content

```
`{{ include('hi', {user: me}) }}`
```

However, this leads to the following errors in the console and nothing is shown.

```
[Vue warn]: Property "include" was accessed during render but is not defined on instance. 
  at <MarkdownExamples.md onVnodeMounted=fn<runCbs> onVnodeUpdated=fn<runCbs> onVnodeUnmounted=fn<runCbs> > 
  at <VitePressContent class="vp-doc _markdown-examples" > 
  at <VPDoc key=4 > 
  at <VPContent> 
  at <Layout> 
  at <VitePressApp>
```

---

```
[Vue warn]: Property "me" was accessed during render but is not defined on instance. 
  at <MarkdownExamples.md onVnodeMounted=fn<runCbs> onVnodeUpdated=fn<runCbs> onVnodeUnmounted=fn<runCbs> > 
  at <VitePressContent class="vp-doc _markdown-examples" > 
  at <VPDoc key=4 > 
  at <VPContent> 
  at <Layout> 
  at <VitePressApp>
```

---

```
[Vue warn]: Unhandled error during execution of render function 
  at <MarkdownExamples.md onVnodeMounted=fn<runCbs> onVnodeUpdated=fn<runCbs> onVnodeUnmounted=fn<runCbs> > 
  at <VitePressContent class="vp-doc _markdown-examples" > 
  at <VPDoc key=4 > 
  at <VPContent> 
  at <Layout> 
  at <VitePressApp>
```

---

```
Uncaught (in promise) TypeError: _ctx.include is not a function
    _sfc_render markdown-examples.md:6
    renderComponentRoot runtime-core.esm-bundler.js:887
    componentUpdateFn runtime-core.esm-bundler.js:6020
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:6151
    setupRenderEffect runtime-core.esm-bundler.js:6161
    mountComponent runtime-core.esm-bundler.js:5929
    processComponent runtime-core.esm-bundler.js:5883
    patch runtime-core.esm-bundler.js:5351
    mountChildren runtime-core.esm-bundler.js:5599
    mountElement runtime-core.esm-bundler.js:5506
    processElement runtime-core.esm-bundler.js:5471
    patch runtime-core.esm-bundler.js:5339
    componentUpdateFn runtime-core.esm-bundler.js:6027
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:6151
    setupRenderEffect runtime-core.esm-bundler.js:6161
    mountComponent runtime-core.esm-bundler.js:5929
    processComponent runtime-core.esm-bundler.js:5883
    patch runtime-core.esm-bundler.js:5351
    mountChildren runtime-core.esm-bundler.js:5599
    mountElement runtime-core.esm-bundler.js:5506
    processElement runtime-core.esm-bundler.js:5471
    patch runtime-core.esm-bundler.js:5339
    mountChildren runtime-core.esm-bundler.js:5599
    mountElement runtime-core.esm-bundler.js:5506
    processElement runtime-core.esm-bundler.js:5471
    patch runtime-core.esm-bundler.js:5339
    mountChildren runtime-core.esm-bundler.js:5599
    mountElement runtime-core.esm-bundler.js:5506
    processElement runtime-core.esm-bundler.js:5471
    patch runtime-core.esm-bundler.js:5339
    mountChildren runtime-core.esm-bundler.js:5599
    mountElement runtime-core.esm-bundler.js:5506
    processElement runtime-core.esm-bundler.js:5471
    patch runtime-core.esm-bundler.js:5339
    mountChildren runtime-core.esm-bundler.js:5599
    mountElement runtime-core.esm-bundler.js:5506
    processElement runtime-core.esm-bundler.js:5471
    patch runtime-core.esm-bundler.js:5339
    componentUpdateFn runtime-core.esm-bundler.js:6027
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:6151
    setupRenderEffect runtime-core.esm-bundler.js:6161
    mountComponent runtime-core.esm-bundler.js:5929
    processComponent runtime-core.esm-bundler.js:5883
    patch runtime-core.esm-bundler.js:5351
    mountChildren runtime-core.esm-bundler.js:5599
    mountElement runtime-core.esm-bundler.js:5506
    processElement runtime-core.esm-bundler.js:5471
    patch runtime-core.esm-bundler.js:5339
    componentUpdateFn runtime-core.esm-bundler.js:6027
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:6151
    setupRenderEffect runtime-core.esm-bundler.js:6161
    mountComponent runtime-core.esm-bundler.js:5929
    processComponent runtime-core.esm-bundler.js:5883
    patch runtime-core.esm-bundler.js:5351
    mountChildren runtime-core.esm-bundler.js:5599
    mountElement runtime-core.esm-bundler.js:5506
    processElement runtime-core.esm-bundler.js:5471
    patch runtime-core.esm-bundler.js:5339
    componentUpdateFn runtime-core.esm-bundler.js:6027
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:6151
    setupRenderEffect runtime-core.esm-bundler.js:6161
    mountComponent runtime-core.esm-bundler.js:5929
    processComponent runtime-core.esm-bundler.js:5883
    patch runtime-core.esm-bundler.js:5351
    componentUpdateFn runtime-core.esm-bundler.js:6027
    run reactivity.esm-bundler.js:177
    update runtime-core.esm-bundler.js:6151
    setupRenderEffect runtime-core.esm-bundler.js:6161
    mountComponent runtime-core.esm-bundler.js:5929
    processComponent runtime-core.esm-bundler.js:5883
    patch runtime-core.esm-bundler.js:5351
    render2 runtime-core.esm-bundler.js:6672
    mount runtime-core.esm-bundler.js:3938
    mount runtime-dom.esm-bundler.js:1535
    <anonymous> index.js:130
    promise callback* index.js:127
    promise callback* index.js:125
```

---

**Also**, if I just try to display ``{{ myvar }}``, I get another similar error (`Property "myvar" was accessed during render but is not defined on instance.`) and nothing is shown. I just want to see the raw code.

### Reproduction

See the example above. It's as simple as that

### Expected behavior

No error

### System Info

```Text
System:
    OS: macOS 12.7.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 412.16 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
  Browsers:
    Chrome: 124.0.6367.202
    Safari: 17.4.1
  npmPackages:
    vitepress: ^1.1.4 => 1.1.4
```

### Additional context

This problem also shows up in Firefox.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-05-14 05:18
Duplicate of #480

**Closed by brc-dd** 2024-05-14 05:18 UTC
Labels: bug: pending triage

**Comment by nbro** [comment] 2024-05-14 13:39
@brc-dd Is the solution written in the documentation? If not, the documentation should be updated.

**Comment by brc-dd** [comment] 2024-05-14 13:46
https://vitepress.dev/guide/using-vue#escaping
