### ISSUE TITLE
Can the third-level headings be displayed?

### ISSUE THREAD

**Issue by sishen654** [vuejs/vitepress#1086] opened 2022-07-29 06:40 UTC
### Is your feature request related to a problem? Please describe.

none

### Describe the solution you'd like

like this
![image](https://user-images.githubusercontent.com/65691266/181698413-71a6bec8-c252-49e3-9c44-131bac9e75cf.png)
instead of：Only up to the second level heading
![image](https://user-images.githubusercontent.com/65691266/181698573-65bfcfda-c4ab-4611-ab4a-a8a91c7e8c2f.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-07-29 07:00
Duplicate of #954

**Closed by brc-dd** 2022-07-29 07:00 UTC
