### ISSUE TITLE
upgrading to vitepress v1.2.2 build error

### ISSUE THREAD

**Issue by Theo-messi** [vuejs/vitepress#3921] opened 2024-05-27 04:11 UTC
### Describe the bug

```sh

  vitepress v1.2.2

✓ building client + server bundles...
✖ rendering pages...
build error:
str.replace is not a function
TypeError: str.replace is not a function
    at escapeHtml$1 (file:///Users/Theo-Messi/Desktop/Theo-Docs/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_@types+node@20.12.12_postcss@8.4.38_search-insi_kwabrcozogw3xguwc456c4glc4/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:19945:14)
    at file:///Users/Theo-Messi/Desktop/Theo-Docs/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_@types+node@20.12.12_postcss@8.4.38_search-insi_kwabrcozogw3xguwc456c4glc4/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46689:24
    at Array.map (<anonymous>)
    at renderAttrs (file:///Users/Theo-Messi/Desktop/Theo-Docs/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_@types+node@20.12.12_postcss@8.4.38_search-insi_kwabrcozogw3xguwc456c4glc4/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46687:29)
    at file:///Users/Theo-Messi/Desktop/Theo-Docs/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_@types+node@20.12.12_postcss@8.4.38_search-insi_kwabrcozogw3xguwc456c4glc4/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46671:33
    at Array.map (<anonymous>)
    at renderHead (file:///Users/Theo-Messi/Desktop/Theo-Docs/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_@types+node@20.12.12_postcss@8.4.38_search-insi_kwabrcozogw3xguwc456c4glc4/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46670:10)
    at renderPage (file:///Users/Theo-Messi/Desktop/Theo-Docs/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_@types+node@20.12.12_postcss@8.4.38_search-insi_kwabrcozogw3xguwc456c4glc4/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46625:13)
    at async pMap.concurrency (file:///Users/Theo-Messi/Desktop/Theo-Docs/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_@types+node@20.12.12_postcss@8.4.38_search-insi_kwabrcozogw3xguwc456c4glc4/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:46770:11)
    at async file:///Users/Theo-Messi/Desktop/Theo-Docs/node_modules/.pnpm/vitepress@1.2.2_@algolia+client-search@4.23.3_@types+node@20.12.12_postcss@8.4.38_search-insi_kwabrcozogw3xguwc456c4glc4/node_modules/vitepress/dist/node/serve-BwR5EPUJ.js:2618:20
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

this is my `package.json`
```json
{
  "scripts": {
    "dev": "vitepress dev",
    "build": "vitepress build",
    "preview": "vitepress preview",
    "prettier": "pnpm exec prettier . --write"
  },
  "devDependencies": {
    "@shikijs/vitepress-twoslash": "^1.6.0",
    "prettier": "3.2.5",
    "vitepress": "1.2.2",
    "vitepress-plugin-google-analytics": "^1.0.2"
  },
  "dependencies": {
    "@types/node": "^20.12.12",
    "@vercel/analytics": "^1.3.1",
    "lint-staged": "^15.2.5",
    "simple-git-hooks": "^2.11.1",
    "vue": "^3.4.27"
  },
  "simple-git-hooks": {
    "pre-commit": "pnpm lint-staged"
  },
  "lint-staged": {
    "*": [
      "prettier --write --ignore-unknown"
    ]
  }
}
```

### Expected behavior

It should build fine

### System Info

```Text
System:
    OS: macOS 14.2.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 32.25 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.1.0 - ~/.nvm/versions/node/v21.1.0/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.2.0 - ~/.nvm/versions/node/v21.1.0/bin/npm
    pnpm: 9.1.2 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.93
    Safari: 17.2.1
  npmPackages:
    vitepress: 1.2.2 => 1.2.2
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-05-27 04:16
Duplicate of #3916. You might have wrong head entries.

**Closed by brc-dd** 2024-05-27 04:16 UTC
Labels: bug: pending triage

**Comment by Theo-messi** [comment] 2024-05-27 04:29
I removed "head" from the config but it still generates the error

**Comment by Theo-messi** [comment] 2024-05-27 04:38
oh! my question
I mistakenly used head in the article. After correcting it, the build went normally.
