### ISSUE TITLE
Extending/Mimicing default components in custom theme

### ISSUE THREAD

**Issue by EtzBetz** [vuejs/vitepress#912] opened 2022-07-03 21:53 UTC
### Is your feature request related to a problem? Please describe.

I want to use the existing structure of VitePress, with kind of the same Layout, but different styling. I was thinking I would just build a custom theme, but it seems like I cannot access e.g. the navbar configs. Or at least I wouldnt know how?

### Describe the solution you'd like

I would like to know how I can build my own custom theme, using all the default data that i would provide otherwise using the default theme.

### Describe alternatives you've considered

Using the default theme but changing it up, but I doubt that it's flexible enough. another thing would be to just for vitepress and implementing my own default theme, but I doubt that it's thought to be done like that.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-07-08 05:23
Yeah we probably should allow this.

Regarding custom theme. You can get the data you need using [`useData`](https://vitepress.vuejs.org/guide/api.html#usedata).

**Comment by brc-dd** [comment] 2022-07-08 05:58
Duplicate of #235

**Closed by brc-dd** 2022-07-08 05:58 UTC
Labels: enhancement, theme
