### ISSUE TITLE
[DOC BUG] url not changing when scrolling side navbar and url jump failure

### ISSUE THREAD

**Issue by bigsnowballhehe** [vuejs/vitepress#2023] opened 2023-03-02 11:38 UTC
### Describe the bug

new version's issue.
[Vite Doc] https://vitepress.vuejs.org/guide/getting-started was build by  .49,
![image](https://user-images.githubusercontent.com/36768323/222415330-4f455a72-5f8c-4961-8264-83e196330da6.png)
At the same time, the problem is that the search jump fails because anchors are not positioned correctly.

[Vue Doc]https://vuejs.org/guide/essentials/event-handling.html#method-handlers build by .29 ,it's normal.

### Reproduction

in production 
https://vitepress.vuejs.org/guide/getting-started

### Expected behavior

URL can correctly locate the element 

### System Info

```shell
browser: Microsoft Edge
Version 110.0.1587.57 (Official build) (64-bit)
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-03-02 12:02
What's the issue? Maybe something edge specific?

https://user-images.githubusercontent.com/40380293/222422729-1193b429-2423-4961-89de-5e9f2f8f9a7c.mov

**Comment by brc-dd** [comment] 2023-03-02 12:04
Oh, if you want scrolling the page to change anchor that we no longer do. Also, vue docs are using the same vitepress version. They just have a custom theme.

**Comment by brc-dd** [comment] 2023-03-02 12:06
Duplicate of #903

**Closed by brc-dd** 2023-03-02 12:06 UTC
Labels: bug: pending triage
