### ISSUE TITLE
how to Allow images to be zoomed in on click

### ISSUE THREAD

**Issue by changbb** [vuejs/vitepress#3064] opened 2023-10-11 07:59 UTC
### Is your feature request related to a problem? Please describe.

在最新的版本中，如何给Markdown文件中的图片添加点击缩放功能呢？
 "vitepress": "1.0.0-rc.14"

### Describe the solution you'd like

 "vitepress": "1.0.0-rc.14"

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-10-11 08:26
Duplicate of #854

**Closed by brc-dd** 2023-10-11 08:26 UTC
