### ISSUE TITLE
新增md内容不满一页时切换页面发生抖动

### ISSUE THREAD

**Issue by Xsir0** [vuejs/vitepress#3711] opened 2024-03-28 02:52 UTC
### Describe the bug

![chrome-capture-2024-3-28](https://github.com/vuejs/vitepress/assets/48853107/18327925-2b04-466d-b395-e5a99d2f9df9)

### Reproduction

chrome 浏览器中新建两个页面，一个内容超过一页，另一个内容不足一页，切换页面即可复现

### Expected behavior

页面正常显示

### System Info

```Text
System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 2.86 GB / 15.83 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.17.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.2989
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by 0xlau** [comment] 2024-03-28 03:02
可以用[stackblitz](https://stackblitz.com/)复现一下，目前我在本地测试并没有这个问题，我用的是1.0.1的版本进行测试的。

**Comment by brc-dd** [comment] 2024-03-28 03:06
Duplicate of #1054

**Closed by brc-dd** 2024-03-28 03:06 UTC
Labels: bug: pending triage
