### ISSUE TITLE
Support for baseAssets ssr config

### ISSUE THREAD

**Issue by treardon17** [vuejs/vitepress#2919] opened 2023-09-07 20:06 UTC
### Is your feature request related to a problem? Please describe.

I would like to create a vitepress site and store it on a cdn, but it will be served from a different location. For example, the files would live somewhere like `https://cdn.example.com/docs/0.1.2+myhash/`, but be served from `https://example.com/docs`. I would like to configure how the asset locations are generated such that all `link`, `script`, and css `url` references are scoped to `https://cdn.example.com/docs/0.1.2+myhash/`.

### Describe the solution you'd like

It appears that `vite-plugin-ssr` has the ability to do what I'm suggesting via the `baseAssets` and cites putting assets on a cdn as a primary example: https://vite-plugin-ssr.com/base-url#baseassets. As far as I can tell, `vitepress` only allows you to configure the `base` parameter, which is close to but not exactly what I'm after.

### Describe alternatives you've considered

I've tried two solutions so far, but neither seem to cover the use case 100%:
1. Try to use `vite-plugin-ssr` in my vitepress config. This ends up throwing warning in the build because it can't resolve a `@theme` alias referenced in vitepress (as well as my other custom aliases I've omitted), and it throws an error saying that "Error: [vite-plugin-ssr][Wrong Usage] At least one page should be defined, see https://vite-plugin-ssr.com/add"

```javascript
export default defineConfig({
  title: 'Docs',
  description: 'Some docs description',
  base: '/docs/',
  srcDir: './src',
  outDir: './dist',
  vite: {
    plugins:[
      ssr({
        baseAssets: cdnPath,
      }),
    ],
  },
});
```

2. Parse the built document via `transformHtml` and change the references after the fact. This is very close, but does not handle the css `url` references.

```javascript
export default defineConfig({
  lang: 'en-US',
  title: 'Docs',
  description: 'Some docs description',
  base: '/docs/',
  transformHtml: (html) => {
    const dom = new JSDOM(html);
    const { head } = dom.window.document;

    Array.from(head.getElementsByTagName('link')).forEach((link) => {
      link.href = transformUrl(link.href);
    });

    Array.from(head.getElementsByTagName('script')).forEach((script) => {
      if (script.type === 'module') {
        script.src = transformUrl(script.src);
      }
    });

    return dom.serialize();
  },
  srcDir: './src',
  outDir: './dist',
});
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-09-07 20:11
Duplicate of #736

**Closed by brc-dd** 2023-09-07 20:11 UTC
