### ISSUE TITLE
Aside Location Order

### ISSUE THREAD

**Issue by JohnCampionJr** [vuejs/vitepress#2134] opened 2023-03-25 17:24 UTC
### Is your feature request related to a problem? Please describe.

I would like the ability to show the aside on the left side of the document.  It is currently coded to the right at all times.

### Describe the solution you'd like

I would like to be able to set the aside location on a page by page basis.   A CSS variable would go a long way here.

### Describe alternatives you've considered

I understand how to set it site-wide with

```
.aside { order: 1 !important }
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-03-25 18:34
Duplicate of #2035

**Closed by brc-dd** 2023-03-25 18:34 UTC

**Comment by JohnCampionJr** [comment] 2023-03-25 20:42
Hi, if I submit a PR for a simple way I came up with, would you be interested?

**Comment by brc-dd** [comment] 2023-03-25 20:44
Yeah sure, just check if other UI is not breaking if one moves it to left.
