### ISSUE TITLE
Dynamic Outline

### ISSUE THREAD

**Issue by wycats** [vuejs/vitepress#1145] opened 2022-08-09 06:51 UTC
### Is your feature request related to a problem? Please describe.

I'm using Vue components that generate headers dynamically, and (of course) the headers I create in Vue components don't appear in the outline.

### Describe the solution you'd like

I'd like to be able to add headers to `page.headers` in my component.

### Describe alternatives you've considered

I tried manipulating `page.headers` in my component from `useData()`, but the headers are read-only at that point.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-08-09 07:56
Duplicate of #785

**Closed by brc-dd** 2022-08-09 07:56 UTC

**Comment by wycats** [comment] 2022-08-18 18:53
@brc-dd this is a little different. #785 suggests automating the process of adding dynamic headers, while this asks for a way to create new entries in the outline list manually.

**Comment by brc-dd** [comment] 2022-08-18 19:32
Ah okay. So regarding manipulating `page.headers`, it won't be possible because we need it to be read-only. Also we are planning to drop that entirely. IG what you can do is use one of the available aside slots and register a custom component for that.

**Comment by wycats** [comment] 2022-08-24 17:27
A couple questions:

- Can I rely on getting the existing markdown headers from useData in a custom component?
- Would it be possible to expose the existing outline component so that I don't have to completely rebuild it (including responsive design, dark mode etc.) from scratch?

**Comment by wycats** [comment] 2022-08-25 00:24
@brc-dd I think that all makes sense. As an OSS maintainer myself, I understand that exposing internals that are still in flux can pose more problems down the road. I appreciate your conservative approach in vitepress relative to vuepress.

I'm ok with any solution as long as it's built on documented, stable features and the way to support responsiveness and dark mode are documented. Does that make sense?
