### ISSUE TITLE
Default theme optional banner(s)

### ISSUE THREAD

**Issue by jasonkuhrt** [vuejs/vitepress#4190] opened 2024-09-09 21:19 UTC
### Is your feature request related to a problem? Please describe.

I was looking at the default theme extension slots for how to add a banner to the website but didn't find anything ideal. I ended up using nav bar content with some hacky CSS to create a new row, but this doesn't look great yet and it already took me a bit of time so far.

![CleanShot 2024-09-09 at 17 20 02@2x](https://github.com/user-attachments/assets/55528d49-351f-4156-b3d0-2b424612f8e0)

### Describe the solution you'd like

I would like there to be a central place to pass some data to a banner content array that when populated will display a strip above the nav bar consisting of a colour and text.

### Describe alternatives you've considered

A slot would work too, but lower level. I think banner is common enough to support is as first class data in the theme config?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-10-02 16:08
Duplicate of #2071

**Closed by brc-dd** 2024-10-02 16:08 UTC
