### ISSUE TITLE
Markdown Parser fails with `{{`

### ISSUE THREAD

**Issue by gossi** [vuejs/vitepress#3053] opened 2023-10-07 09:53 UTC
### Describe the bug

I'm documenting some ember addon. Ember and Vue use double curly syntax. Here is my markdown snippet that currently has a parser error:

```md
Thus, a code such as `{{on "click" inc}}` would break as Ember is not able to make that association.
```

Which fails with the error message:

```
[plugin:vite:vue] Error parsing JavaScript expression: Unexpected token, expected "," (1:4)
```

Here the screenshot of the error message. The extracted code snippet is actually not the real reason - I guess the parser is confused here.

<img width="886" alt="Bildschirmfoto 2023-10-07 um 11 48 42" src="https://github.com/vuejs/vitepress/assets/283700/6e1ec7a3-92e5-4537-856e-57813de3227c">

### Reproduction

Enter the snippet above into any markdown file and vitepress will show the error.

### Expected behavior

Within code backticks, I'd expect vitepress not trying to execute vue code.

### System Info

```Text
System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 11.69 MB / 16.00 GB
    Shell: 3.6.1 - /usr/local/bin/fish
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.5.1 - ~/.volta/tools/image/node/18.16.0/bin/npm
    pnpm: 8.8.0 - ~/.volta/bin/pnpm
    Watchman: 2023.08.14.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 103.1.41.100
    Chrome: 117.0.5938.149
    Edge: 117.0.2045.47
    Safari: 16.5.2
  npmPackages:
    vitepress: ^1.0.0-rc.20 => 1.0.0-rc.20
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-10-07 09:59
Duplicate of #480

**Closed by brc-dd** 2023-10-07 09:59 UTC
Labels: bug: pending triage
