### ISSUE TITLE
HMR faild if config in other files

### ISSUE THREAD

**Issue by JackFGreen** [vuejs/vitepress#1092] opened 2022-08-01 10:06 UTC
### Describe the bug

```ts
// docs/.vitepress/common.ts
export const title = 'xxx'
```

```ts
// docs/.vitepress/config.ts
import { title } from './common'
export default defineConfig({
  title
})
```

HMR faild if i mofidy `title` in `common.ts`

### Reproduction

Mofidy `title` in `common.ts`, page title will not change

### Expected behavior

page title will change

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 286.90 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.3/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 103.0
    Safari: 15.4
  npmPackages:
    vitepress: ^1.0.0-alpha.4 => 1.0.0-alpha.4
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-08-01 10:28
Duplicate of #581

**Closed by brc-dd** 2022-08-01 10:28 UTC
Labels: bug: pending triage
