### ISSUE TITLE
TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by Topthinking** [vuejs/vitepress#904] opened 2022-07-03 09:32 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/13382821/177033799-4f4c28c1-3dd1-4f3b-8f0d-2e12ea6615e5.png)

docs/vite.config.ts
```ts
import { defineConfig } from "vite";
import vueJsx from "@vitejs/plugin-vue-jsx";
import legacy from "@vitejs/plugin-legacy";

export default defineConfig({
  plugins: [
    vueJsx(),
    legacy({
      targets: ["defaults", "not IE 11"],
    }),
  ],
});

```

### System Info

```shell
vite/3.0.0-beta.5 darwin-x64 node-v14.19.2
```

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-07-03 09:44
Duplicate of #309

**Closed by brc-dd** 2022-07-03 09:44 UTC
Labels: bug: pending triage

**Comment by Topthinking** [comment] 2022-07-03 09:48
那预计啥时解决

**Comment by Topthinking** [comment] 2022-07-03 09:48
@brc-dd

**Comment by brc-dd** [comment] 2022-07-03 09:54
I don't have any ETA on this. Legacy plugin only affects less than 6% users, we don't have plans on prioritizing it. PRs are welcome though if someone could figure out the cause.
