### ISSUE TITLE
how to partially build

### ISSUE THREAD

**Issue by thunderwin** [vuejs/vitepress#4182] opened 2024-09-06 09:32 UTC
### Is your feature request related to a problem? Please describe.

I have many pages, so how to partially build.

### Describe the solution you'd like

I have to build all the pages even I only add a new one?

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-09-06 09:52
Duplicate of #1991

**Closed by brc-dd** 2024-09-06 09:52 UTC
