### ISSUE TITLE
Unexpected outline behavior

### ISSUE THREAD

**Issue by road2coder** [vuejs/vitepress#2725] opened 2023-08-03 09:13 UTC
### Describe the bug

When I click on an item above the currently active item in the outline, the marker first appears above the target item, and then appears in the correct place. Is this intentional?

https://github.com/vuejs/vitepress/assets/84114146/77ad4b5a-dc13-4acd-8704-f261124594f9

### Reproduction

The VitePress official website exhibits the same phenomenon. 

### Expected behavior

The marker appears in the correct place at the first time

### System Info

```sh
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 3.84 GB / 14.85 GB
  Binaries:
    Node: 16.19.1 - D:\Environment\nodejs\node.EXE
    Yarn: 1.22.19 - D:\Environment\nodejs\yarn.CMD
    npm: 8.19.3 - D:\Environment\nodejs\npm.CMD
    pnpm: 8.6.5 - D:\Environment\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-beta.7 => 1.0.0-beta.7
```

### Additional context

Changing "throttleAndDebounce" in the [outline.js](https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/composables/outline.ts) to a simple debounce function can solve this issue.

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-08-03 09:17
Duplicate of #2665

**Closed by brc-dd** 2023-08-03 09:17 UTC
Labels: bug: pending triage
