### ISSUE TITLE
local search should return doc section too (maybe optionally)

### ISSUE THREAD

**Issue by pberto** [vuejs/vitepress#3437] opened 2024-01-10 23:44 UTC
This is more of a question, but if there is no solution then it should be moved as a feature suggestion.

So I am using local search and rather happy with it, the only big issue is that I want to know the parent doc (scope) since my documentation has many pages with the same structure, example:

<img width="422" alt="image" src="https://github.com/vuejs/vitepress/assets/254052/eebae5d2-8869-4ec7-8873-c1c8d90faae2">

As you can see in my documentation I have two pages with a main headers "#" called "Object Attributes", one relates to product A and one relates to Product B but local search does not let me know the parent directory of the documentation and just showed me both without me knowing which scope they are part of.

the file structure on disk is:

```
/productA/object-attributes.md (the first line of this md is "# Object Attributes")
/productB/object-attributes.md (aswell the first line of this md is "# Object Attributes")
```

What I would like to see is the name of the directory productA or productB as an additional info in the local search result or any other way that provides me this info (I would expect local search to be able to provide this info somehow, but if not I am completely fine to put in the front matter something like `parent: productA`) but I need some info on how to query it in the local search.

There must be a way to do this, I just cannot find how :(

**Comment by zonemeen** [comment] 2024-01-11 01:56
Duplicate of https://github.com/vuejs/vitepress/issues/3192. Let's track this at there.

**Closed** 2024-01-11 01:57 UTC
