### ISSUE TITLE
` ` character (%20) in markdown filename cannot work after build

### ISSUE THREAD

**Issue by gyhyfj** [vuejs/vitepress#2296] opened 2023-04-26 10:03 UTC
### Describe the bug

For example:
If the markdown filename is `01 overview.md`,  and the link of this file in `.vitepress/config.ts` is `link: 'path/to/01 overview' `,
then:
1. If I run `docs:dev`, I can access this page by `path/to/01%20overview`, everything works well.
2. If I run `docs:build`, it doesn't work, and return 404

### Reproduction

As above

### Expected behavior

blank character in markdown file's filename should still work after build 

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 6.17 GB / 15.92 GB
  Binaries:
    Node: 18.16.0 - D:\Program Files\NodeJS\node.EXE
    npm: 9.6.4 - D:\Program Files\NodeJS\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.58)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitepress: latest => 1.0.0-alpha.74
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-04-27 13:52
IDK but having spaces in URLs seems like a pretty bad idea anyway 🤷‍♂️

**Comment by brc-dd** [comment] 2023-04-30 08:39
Duplicate of #573

**Closed by brc-dd** 2023-04-30 08:39 UTC
Labels: bug, build
