### ISSUE TITLE
Problems with cyrillic symbol in the anchor links

### ISSUE THREAD

**Issue by stereshko** [vuejs/vitepress#299] opened 2021-05-15 11:15 UTC
**Describe the bug**
Cyrillic "л" is replaced by Latin "n" in the anchor links.

**To Reproduce**
- `git clone https://github.com/stereshko/tailwind-jit-vitepress.git`
- `yarn install`
- `yarn docs:dev`
- visit `localhost:3000`
- check anchor links

**Expected behavior**
Anchor links `#загоnовок` => `#заголовок`, `#подзагоnовок` => `#подзаголовок`, `#лn` => `#лл`,

**System Info**
- vitepress version: 0.13.2
- vite version: 2.2.4
- Node version: 14.16.1
- OS version: Windows 10 Pro 20H2

**Comment by kiaking** [comment] 2022-05-23 07:06
Thanks for the report! Closing due to not being able to reproduce this in `next-theme`.

**Closed by kiaking** 2022-05-23 07:06 UTC
