### ISSUE TITLE
Markdown section's dom padding is not stable

### ISSUE THREAD

**Issue by fuzhenn** [vuejs/vitepress#3775] opened 2024-04-10 09:56 UTC
### Describe the bug

The padding of the markdown content dom is not stable, causing the sidebar to shift slightly when switching between markdowns via the sidebar.

### Reproduction

Referring to the link below, when switching between clicking on link 1 and link 2 at bottom of the sidebar, you will notice that the sidebar is slightly shifting.

https://vitepress.dev/zh/guide/mpa-mode

![image](https://github.com/vuejs/vitepress/assets/13678919/a4609ec2-77a1-400e-8f3e-74193248ce75)

### Expected behavior

The sidebar remains stable

### System Info

```Text
System:
    OS: Windows 11 10.0.22631
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 5.25 GB / 15.94 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.81)
  npmPackages:
    vitepress: 1.0.1 => 1.0.1
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-04-10 10:01
Can you show a screen recording, seems to be working fine for me 👀

**Comment by fuzhenn** [comment] 2024-04-10 10:04
Of course!
![screenshot](https://github.com/vuejs/vitepress/assets/13678919/2e891c1e-f5a1-4e32-9b80-4bdf47a6e6e0)

**Comment by brc-dd** [comment] 2024-04-10 10:07
Ah, it's windows thing. Duplicate of #1054

**Closed by brc-dd** 2024-04-10 10:07 UTC
Labels: need more info

**Comment by fuzhenn** [comment] 2024-04-10 10:08
Got it, Thanks!
