### ISSUE TITLE
All Page Frontmatter Info ?

### ISSUE THREAD

**Issue by Minseok0917** [vuejs/vitepress#692] opened 2022-06-01 16:18 UTC
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

I'm sorry. I posted the wrong question (https://github.com/vuejs/vitepress/issues/691)
Is there a way to get Frontmatter and Path information for all files converted from Markdown to HTML?

I want to create a page that shows a list of customized articles using "frontmatter"

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-06-01 16:41
Hi! This is a duplicate of #96.

**Closed by brc-dd** 2022-06-01 16:41 UTC
