### ISSUE TITLE
Cannot be packaged with file name in Chinese

### ISSUE THREAD

**Issue by heny** [vuejs/vitepress#217] opened 2021-01-31 11:23 UTC
A packaging error occurred while using the Chinese Markdown filename
yarn build

yarn run v1.22.4
$ vitepress build docs
vitepress v0.11.5
vite v2.0.0-beta.60
- building client + server bundles...Language does not exist: sh
✓ building client + server bundles...
- rendering pages...Error: Cannot find module './%E5%85%B6%E4%BB%96%E7%AC%94%E8%AE%B0.md.js'
Require stack:
- E:\item\vue\vite-build-test\node_modules\vitepress\dist\client\app\temp\app.js
- E:\item\vue\vite-build-test\node_modules\vitepress\dist\node\build\render.js
- E:\item\vue\vite-build-test\node_modules\vitepress\dist\node\build\build.js
- E:\item\vue\vite-build-test\node_modules\vitepress\dist\node\index.js
- E:\item\vue\vite-build-test\node_modules\vitepress\dist\node\cli.js
- E:\item\vue\vite-build-test\node_modules\vitepress\bin\vitepress.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at E:\item\vue\vite-build-test\node_modules\vitepress\dist\client\app\temp\app.js:1659:12
    at loadPage (E:\item\vue\vite-build-test\node_modules\vitepress\dist\client\app\temp\app.js:75:18)
    at Object.go (E:\item\vue\vite-build-test\node_modules\vitepress\dist\client\app\temp\app.js:68:12)
    at Object.renderPage (E:\item\vue\vite-build-test\node_modules\vitepress\dist\node\build\render.js:18:12)
    at Object.build (E:\item\vue\vite-build-test\node_modules\vitepress\dist\node\build\build.js:29:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\item\\vue\\vite-build-test\\node_modules\\vitepress\\dist\\client\\app\\temp\\app.js',
    'E:\\item\\vue\\vite-build-test\\node_modules\\vitepress\\dist\\node\\build\\render.js',
    'E:\\item\\vue\\vite-build-test\\node_modules\\vitepress\\dist\\node\\build\\build.js',
    'E:\\item\\vue\\vite-build-test\\node_modules\\vitepress\\dist\\node\\index.js',
    'E:\\item\\vue\\vite-build-test\\node_modules\\vitepress\\dist\\node\\cli.js',
    'E:\\item\\vue\\vite-build-test\\node_modules\\vitepress\\bin\\vitepress.js'
  ]
}
✖ rendering pages...
build error:
 TypeError: Cannot destructure property 'frontmatter' of 'route.data' as it is null.
    at E:\item\vue\vite-build-test\node_modules\vitepress\dist\client\app\temp\app.js:1318:14
    at ComputedRefImpl.reactiveEffect [as effect] (E:\item\vue\vite-build-test\node_modules\@vue\reactivity\dist\reactivity.cjs.prod.js:46:24)
    at ComputedRefImpl.get value [as value] (E:\item\vue\vite-build-test\node_modules\@vue\reactivity\dist\reactivity.cjs.prod.js:774:32)
    at E:\item\vue\vite-build-test\node_modules\vitepress\dist\client\app\temp\app.js:1338:36
    at ComputedRefImpl.reactiveEffect [as effect] (E:\item\vue\vite-build-test\node_modules\@vue\reactivity\dist\reactivity.cjs.prod.js:46:24)
    at ComputedRefImpl.get value [as value] (E:\item\vue\vite-build-test\node_modules\@vue\reactivity\dist\reactivity.cjs.prod.js:774:32)
    at Object.unref (E:\item\vue\vite-build-test\node_modules\@vue\reactivity\dist\reactivity.cjs.prod.js:693:29)
    at E:\item\vue\vite-build-test\node_modules\vitepress\dist\client\app\temp\app.js:1347:71
    at renderComponentSubTree (E:\item\vue\vite-build-test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:208:13)
    at renderComponentVNode (E:\item\vue\vite-build-test\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:174:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kiaking** [comment] 2021-02-10 16:30
Confirmed. Seems like multi byte file name gets encoded in some special value. Not sure where the root cause is. Need to look into it.

**Comment by brc-dd** [comment] 2022-05-30 06:35
Was fixed by your PR #262.

**Closed by brc-dd** 2022-05-30 06:35 UTC
Labels: bug
