### ISSUE TITLE
sidebar 超链接样式错位

### ISSUE THREAD

**Issue by jarvis-tang** [vuejs/vitepress#1869] opened 2023-01-31 12:31 UTC
### Describe the bug

见截图，超链接的箭头图标换行了。

<img width="964" alt="image" src="https://user-images.githubusercontent.com/22316055/215759946-0ceba7a1-6d1f-4e73-8b38-2c87dfd2479c.png">

### Reproduction

好像是从 alpha.37 版本开始的，到了 alpha.44 版本时，问题还在。

### Expected behavior

不换行，跟随在文字后面。

### System Info

```shell
无
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-02-01 14:08
Duplicate of #1864

**Closed by brc-dd** 2023-02-01 14:08 UTC
Labels: bug: pending triage
