### ISSUE TITLE
Configurable index file name

### ISSUE THREAD

**Issue by georgkrause** [vuejs/vitepress#524] opened 2022-02-10 13:23 UTC
### Is your feature request related to a problem? Please describe.

I am building a Vue component library. Each vue component has some files which live next to it, eg 

* tests
* documentation
* the component itself

In order to keep the project directory tree structured, we create a directory for each component containing all required files, maybe even more than listed above.

We use vitepress for the documentation, which works great, except: I'd like to name the markdown file for the documentation something more useful, eg `Documentation.md` or whatever.

### Describe the solution you'd like

By reading the source code there is a [regex definition](https://github.com/vuejs/vitepress/blob/294b1d281750b3abc321b05d0fdb88f355d298cf/src/node/markdown/plugins/link.ts#L10) for searching for the index file. It would be really nice to have this configurable. 

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/master/.github/contributing.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-06-01 05:48
We don't use that regex "for searching for the index file". It is being simply used to transform links inside your markdown content. We don't actually search for index file, we generate a `foo.html` corresponding to every `foo.md`. It is the browsers that request `index.html` by default. If we try to address your feature, it will require us to generate an `index.html` file corresponding to your `foo.md` file, and updating the links to treat `/foo` as `/`. There is no ETA on when (or if) this feature will arrive. For the time being you can solve this by using rewrite rules provided by your hosting/dns provider.

**Comment by kiaking** [comment] 2022-06-01 12:13
As @brc-dd mentioned, I'm not sure if we really need this feature. But the only use case I can think of is to name it `README.md`, so that the docs becomes readable when viewing on GitHub too.

But, I don't think that many people would actually do that 😅 (If you have a VitePress site, just visit there you know)

**Comment by georgkrause** [comment] 2022-06-02 08:31
I understand your point of view and I can only understand that this might be out of scope. On the other hand, I think the usecase I described is a valid one. We want to have living documentation next to our code and have a file called `index.md` in each repository isn't really helpful. Even if my idea of adjusting the regex was wrong and a result of my lack of understanding the code, maybe we can find another solution which makes vitepress a even better fit for us? :)

**Comment by politician** [comment] 2022-06-03 12:08
This issue is a duplicate of https://github.com/vuejs/vitepress/issues/280

And btw, I agree this should be addressed 🙄

**Comment by kiaking** [comment] 2022-06-06 06:29
OK, let's follow up this at #280 👍

**Closed by kiaking** 2022-06-06 06:29 UTC
Labels: enhancement
