### ISSUE TITLE
When building getting this error: Rollup failed to resolve import "vue/server-renderer" from "..."

### ISSUE THREAD

**Issue by nick-kadutskyi** [vuejs/vitepress#2713] opened 2023-07-31 01:00 UTC
### Describe the bug

When I try to run `vitepress build` I get:

```
[vite]: Rollup failed to resolve import "vue/server-renderer" from "/Users/nick/Library/Mobile Documents/27N4MQEA55~pro~writer/Documents/Notes/Docs/index.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
✖ building client + server bundles...
build error:
Error: [vite]: Rollup failed to resolve import "vue/server-renderer" from "/Users/nick/Library/Mobile Documents/27N4MQEA55~pro~writer/Documents/Notes/Docs/index.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///Users/nick/Developer/PE/0023/vitepress/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:48088:27)
    at onRollupWarning (file:///Users/nick/Developer/PE/0023/vitepress/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:48120:9)
    at onwarn (file:///Users/nick/Developer/PE/0023/vitepress/node_modules/.pnpm/vite@4.4.7_@types+node@20.4.5/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:47848:13)
    at file:///Users/nick/Developer/PE/0023/vitepress/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:24090:13
    at Object.logger [as onLog] (file:///Users/nick/Developer/PE/0023/vitepress/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:25762:9)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/nick/Developer/PE/0023/vitepress/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:24676:26)
    at file:///Users/nick/Developer/PE/0023/vitepress/node_modules/.pnpm/rollup@3.27.0/node_modules/rollup/dist/es/shared/node-entry.js:24636:26

```

### Reproduction

1. Set `srcDir` parameter to some folder outside of the root project.
2. Run `vitepress build`
3. Get the error

### Expected behavior

Not getting the error during build while having `srcDir` set to a folder outside of the project root

### System Info

```sh
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 63.59 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
    pnpm: 8.6.10 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.6
    Safari Technology Preview: 17.0
  npmPackages:
    vitepress: 1.0.0-beta.7 => 1.0.0-beta.7
```

### Additional context

When I move src folder into the project root and point to it in `srcDir` it works properly.

When I create a symlink in the project root and point `srcDir` to it I get the same error.

If I follow suggestions in the error message to set `build.rollupOptions.external` like this:
```js
    vite: {
        build: {
            rollupOptions: {
                external: ["vue/server-renderer", "vue"]
            }
        }
    }
```
I get it to build successfully but then interactions (collapsed items in sidebar) won't work because it can't find vue.

Overall my goal is to have vitepress project and markdown files completely separate from each other. 

### Validations

- [x] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Aganxx** [comment] 2023-08-01 02:31
I have a similar problem
```
✖ building client + server bundles...
build error:
Error: Could not load vue/dist/vue.esm-bundler.js/server-renderer (imported by node_modules/.pnpm/vitepress@1.0.0-alpha.63_stylus@0.59.0/node_modules/vitepress/dist/client/app/ssr.js): ENOENT: no such file or directory, open 'vue/dist/vue.esm-bundler.js/server-renderer'
```
But server-renderer doesn't appear to exist in the file

**Comment by brc-dd** [comment] 2023-08-03 06:02
Not reproducible. Probably was caused by #2689. Should be fixed in next release. Try using beta 6 for now.

**Closed by brc-dd** 2023-08-03 06:02 UTC
Labels: bug: pending triage
