### ISSUE TITLE
Using the `:` syntax in a Markdown table will result in an error: [plugin:vite:vue] v-bind is missing expression.

### ISSUE THREAD

**Issue by qiuxchao** [vuejs/vitepress#2126] opened 2023-03-23 03:42 UTC
### Describe the bug

As the title says, VitePress fails when I write the following in Markdown:

```md
| 数字       | 格式    |   输出    |                         描述 |
| ---------- | :------ | :-------: | ---------------------------: |
| 3.1415926  | {:.2f}  |   3.14    |             保留小数点后两位 |
| 3.1415926  | {:+.2f} |   +3.14   |       带符号保留小数点后两位 |
| -1         | {:+.2f} |   -1.00   |       带符号保留小数点后两位 |
| 2.71828    | {:.0f}  |     3     |                     不带小数 |
| 5          | {:0>2d} |    05     | 数字补零(填充左边, 宽度为 2) |
| 5          | {:x<4d} |   5xxx    | 数字补 x(填充右边, 宽度为 4) |
| 10         | {:x<4d} |   10xx    | 数字补 x(填充右边, 宽度为 4) |
| 1000000    | {:,}    | 1,000,000 |         以逗号分隔的数字格式 |
| 0.25       | {:.2%}  |  25.00%   |                   百分比格式 |
| 1000000000 | {:.2e}  | 1.00e+09  |                     指数记法 |
| 13         | {:10d}  |    13     |       右对齐(默认,宽度为 10) |
| 13         | {:<10d} |    13     |            左对齐(宽度为 10) |
| 13         | {:^10d} |    13     |          中间对齐(宽度为 10) |
```

### Reproduction

https://stackblitz.com/edit/vite-xlyckk?file=docs/example.md

### Expected behavior

VitePress works fine when I use `:` in Markdown table

### System Info

```shell
System:
    OS: macOS 11.6.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 474.80 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
Browsers:
    Chrome: 111.0.5563.110
    Edge: 111.0.1661.44
    Safari: 14.1.2
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-03-23 03:49
Duplicate of #449

**Closed by brc-dd** 2023-03-23 03:49 UTC
Labels: bug: pending triage

**Comment by brc-dd** [comment] 2023-03-23 03:51
Either disable markdown-it-attrs:

```ts
// .vitepress/config.ts
// ...
  markdown: {
    attrs: {
      disable: true,
    },
  },
// ...
```

Or escape`{`/`}` in your markdown like this:

````md
| 数字       | 格式      |   输出    |                         描述 |
| ---------- | :-------- | :-------: | ---------------------------: |
| 3.1415926  | `{:.2f}`  |   3.14    |             保留小数点后两位 |
| 3.1415926  | `{:+.2f}` |   +3.14   |       带符号保留小数点后两位 |
| -1         | `{:+.2f}` |   -1.00   |       带符号保留小数点后两位 |
| 2.71828    | `{:.0f}`  |     3     |                     不带小数 |
| 5          | `{:0>2d}` |    05     | 数字补零(填充左边, 宽度为 2) |
| 5          | `{:x<4d}` |   5xxx    | 数字补 x(填充右边, 宽度为 4) |
| 10         | `{:x<4d}` |   10xx    | 数字补 x(填充右边, 宽度为 4) |
| 1000000    | `{:,}`    | 1,000,000 |         以逗号分隔的数字格式 |
| 0.25       | `{:.2%}`  |  25.00%   |                   百分比格式 |
| 1000000000 | `{:.2e}`  | 1.00e+09  |                     指数记法 |
| 13         | `{:10d}`  |    13     |       右对齐(默认,宽度为 10) |
| 13         | `{:<10d}` |    13     |            左对齐(宽度为 10) |
| 13         | `{:^10d}` |    13     |          中间对齐(宽度为 10) |
````
