### ISSUE TITLE
使用vantUI时，抛出了一个错误，Unknown file extension ".css"...

### ISSUE THREAD

**Issue by JanYork** [vuejs/vitepress#1621] opened 2022-11-18 08:03 UTC
### Describe the bug

build error:
 TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for C:\Users\woo-m\Desktop\ToTimeMail\node_modules\vant\es\style\base.css

### Reproduction

无法重现

### Expected behavior

build error:
 TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for C:\Users\woo-m\Desktop\ToTimeMail\node_modules\vant\es\style\base.css

### System Info

```shell
build error:
 TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for C:\Users\woo-m\Desktop\ToTimeMail\node_modules\vant\es\style\base.css
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by HelloGwkki** [comment] 2022-11-27 13:25
Same problem - can't build the project when using Vuetify 3.

### Log
```
yarn build
yarn run v1.22.19
$ vitepress build
vitepress v1.0.0-alpha.26
✓ building client + server bundles...
build error:
 TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for E:\project\vitepress\node_modules\vuetify\lib\components\VCode\VCode.css
    at new NodeError (node:internal/errors:387:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:76:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:118:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)   
    at nextLoad (node:internal/modules/esm/loader:165:28)   
    at ESMLoader.load (node:internal/modules/esm/loader:608:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:464:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:483:17)

    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:483:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:441:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
error Command failed with exit code 1.
```

### Reproduction
https://stackblitz.com/edit/vite-dxpojx?file=docs/.vitepress/theme/Layout.vue

**Comment by HelloGwkki** [comment] 2022-11-27 13:49
#1465

**Comment by brc-dd** [comment] 2022-11-27 14:09
Duplicate of #1465 

Something like `{ ssr: { noExternal: ['vant'] } }` should work for you.

**Closed by brc-dd** 2022-11-27 14:09 UTC
Labels: bug: pending triage
