### ISSUE TITLE
Markdown links don't work with interpolated / variable strings

### ISSUE THREAD

**Issue by pfei5** [vuejs/vitepress#2304] opened 2023-04-27 13:19 UTC
### Describe the bug

I'd like to be able to create dynamic links, something like:

```vue
// docs/index.md

<script setup>
  const link = './openapi/my-cool-endpoint';
</script>

[Hey, check this out]({{ link }})
```

This code isn't rendered as a link but as text instead:

```html
<p>[Hey, check this out](./openapi/my-cool-endpoint)</p>
```

### Reproduction

Add a link inside a markdown file and use an interpolated string as the link target.

### Expected behavior

A link is generated with the interpolated string a the target.

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 198.78 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Brave Browser: 110.1.48.171
    Chrome: 112.0.5615.137
    Firefox: 112.0.1
    Safari: 16.4
  npmPackages:
    vitepress: 1.0.0-alpha.74 => 1.0.0-alpha.74
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-04-27 13:21
Duplicate of #2240, https://github.com/vuejs/vitepress/issues/2099#issuecomment-1481350268

**Closed by brc-dd** 2023-04-27 13:21 UTC
Labels: bug: pending triage
