### ISSUE TITLE
import code snippets can't HMR

### ISSUE THREAD

**Issue by yl-199807** [vuejs/vitepress#1061] opened 2022-07-25 07:12 UTC
### Is your feature request related to a problem? Please describe.

<<< in md can not HMR

* git clone https://github.com/yl-199807/vitepress-test-hmr.git
*  yarn
*  yarn docs:dev

![image](https://user-images.githubusercontent.com/76727895/180717392-66e3dce5-8337-4f3a-b457-db591da7fd73.png)

In development environment, when importe file update，page can't hot update.

### Describe the solution you'd like

Page follow importing file update

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by yl-199807** [comment] 2022-07-25 07:14
use "vitepress": "^1.0.0-alpha.4"

**Comment by brc-dd** [comment] 2022-07-25 07:17
duplicate of #117

**Closed by brc-dd** 2022-07-25 07:17 UTC
