### ISSUE TITLE
Config srcDir in app config could take array of paths

### ISSUE THREAD

**Issue by VasekProchazka** [vuejs/vitepress#1949] opened 2023-02-16 05:39 UTC
### Is your feature request related to a problem? Please describe.

I have case, where I need to load my markdowns from multiple sources

### Describe the solution you'd like

I want to use `srcDir` option from configuration like array: ['.', '../../']

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-02-16 05:47
Duplicate of #1571

**Closed by brc-dd** 2023-02-16 05:47 UTC
