### ISSUE TITLE
Build with Relative URLs

### ISSUE THREAD

**Issue by gerripeach** [vuejs/vitepress#3673] opened 2024-03-21 07:41 UTC
### Is your feature request related to a problem? Please describe.

I can not build to use the site "offline", so open index.html directly in browser.

### Describe the solution you'd like

I want to be able to use relative URLS

e.g. asset loading in index.html defaults to this
````
    <link rel="modulepreload" href="/assets/chunks/framework.efMJGC9V.js">
    <link rel="modulepreload" href="/assets/chunks/theme.DRnY8Jar.js">
    <link rel="modulepreload" href="/assets/index.md.BTLj63lk.lean.js">
`````

these links starting with a slath won't work if I open index.html directly in the browser

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2024-03-21 11:15
Won’t fix. Duplicate of many more such issues (search yourself).

**Closed by brc-dd** 2024-03-21 11:15 UTC
