### ISSUE TITLE
pnpm add -D vitepress missing peers

### ISSUE THREAD

**Issue by laoshaw** [vuejs/vitepress#525] opened 2022-02-11 01:46 UTC
### Describe the bug

`pnpm init -y && pnpm add -D vitepress`

```
devDependencies:
+ vitepress 0.21.6

 WARN  Issues with peer dependencies found
.
└─┬ vitepress
  └─┬ @docsearch/js
    └─┬ @docsearch/react
      ├── ✕ missing peer @types/react@">= 16.8.0 < 18.0.0"
      ├── ✕ missing peer react@">= 16.8.0 < 18.0.0"
      ├── ✕ missing peer react-dom@">= 16.8.0 < 18.0.0"
      └─┬ @algolia/autocomplete-preset-algolia
        └── ✕ missing peer @algolia/client-search@^4.9.1
Peer dependencies that should be installed:
  @algolia/client-search@^4.9.1      react-dom@">= 16.8.0 < 18.0.0"     
  @types/react@">= 16.8.0 < 18.0.0"  react@">= 16.8.0 < 18.0.0"  
```

using yarn or npm install has no such 'missing peer' warnings

### Reproduction

`pnpm init -y && pnpm add -D vitepress`

### Expected behavior

no 'missing peer' errors

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Memory: 686.82 MB / 15.61 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Chromium: 87.0.4280.66
    Firefox: 96.0
  npmPackages:
    vitepress: ^0.21.6 => 0.21.6 
```
```


### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2022-02-11 07:44
Duplicate of #472

**Closed** 2022-05-19 10:50 UTC
Labels: duplicate
