### ISSUE TITLE
Route links don't work in 404 component, in build mode

### ISSUE THREAD

**Issue by canicjusz** [vuejs/vitepress#221] opened 2021-02-04 10:36 UTC
**Describe the bug**
Route links redirect to the correct route, but the content of the page is not rendered. Instead error is returned. In dev mode everything works as expected.

**To Reproduce**
1. add custom 404 component;
2. add link to `index.md` in the component, like: `<a href="/">index.md</a>`;
3. run `vitepress build`;
4. go to non-existing route and click on the link.

**Expected behavior**
The page should be rendered.

**System Info**
- vitepress version: 0.11.5
- vite version: 2.0.0-beta.64
- Node version: v12.18.3
- OS version: Pop!_OS 20.10

**Additional context**
The error it is returning:
![image](https://user-images.githubusercontent.com/55652950/106880088-3d2b0580-66dc-11eb-9ac4-8629b25d81dd.png)

code: https://github.com/canicjusz/vitepress-route-bug

**Comment by kleisauke** [comment] 2022-01-26 13:39
This issue still occurs on v0.21.6. In addition to the repository mentioned above, here's a live demo of the bug:
https://t0.nl/404
(Click on `Take me home.` to reproduce)

**Comment by kleisauke** [comment] 2022-01-26 17:47
It seems that this is a consequence of a hydration node mismatch. I noticed this in a debug build:
```
Hydration node mismatch:
- Client vnode: main 
- Server rendered DOM: <!--[--> (start of fragment)
Hydration completed but contains mismatches.
```

As a possible workaround/solution, one could create a custom 404 page with the appropriate content. For example:

`.vitepress/theme/index.js`
```javascript
import DefaultTheme from 'vitepress/theme'

export default {
  ...DefaultTheme,
  enhanceApp({ app }) {
    app.component('NotFound', DefaultTheme.NotFound)
  }
}
```

`404.md`
```markdown
---
title: Not found
---

<NotFound />
```

After that, make sure to point non-matching routes to `404.html`. In nginx, this would be:
```nginx
server {
    ...

    index index.html;

    error_page 404 /404.html;

    ...
}
```

I'll keep the above mentioned reproducer online for a while, allowing someone else to reproduce it.

**Comment by brc-dd** [comment] 2022-04-13 19:20
Is this issue present on latest version? I am not able to reproduce this with the provided repository.

https://user-images.githubusercontent.com/40380293/163254269-2a543e3f-e101-4cd0-b877-0ea70e2a2c7c.mp4

**Comment by kiaking** [comment] 2022-05-23 10:02
Seems like this is resolved in latest version. Please feel free to open another issue if you encounter this again!

**Closed by kiaking** 2022-05-23 10:02 UTC
Labels: bug: pending triage
