### ISSUE TITLE
能否增加一个图片点击放大的功能。

### ISSUE THREAD

**Issue by Lxx-c** [vuejs/vitepress#2674] opened 2023-07-24 02:40 UTC
### Is your feature request related to a problem? Please describe.

当我在文档里插入图片发布后，图片中有部分内容在页面上较为模糊。我试过markdown-it-custom-attrs插件，但是好像没有生效。

### Describe the solution you'd like

在vitepress中集成图片灯箱的功能，或者有什么办法可以集成相关组件（希望给一个示例）

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by zonemeen** [comment] 2023-07-24 04:05
Duplicate of https://github.com/vuejs/vitepress/issues/854

**Closed by zonemeen** 2023-07-24 04:05 UTC
