### ISSUE TITLE
Page hangs on search when clicking detail view in search box

### ISSUE THREAD

**Issue by arcqiufeng** [vuejs/vitepress#2321] opened 2023-04-30 10:30 UTC
### Describe the bug

Maybe it is not a bug but a performance issue.

I found an alpha 75 update and couldn't wait to update it to see if the detail view issue for searches had been fixed.

The problem still exists. When the detail view is turned off (it's grayed out by default and not enabled, so don't click on it), everything is fine and works fine. When I click on the details button, the whole page stops responding.

My vitepress site has about 98 markdown files totaling about 1.70M. They are all in Chinese. Is this too heavy for local search engines?

### Reproduction

Page hangs on search if click on detailview in search box

### Expected behavior

Expected it works on detail mode.

### System Info

```sh
npx envinfo --system --npmPackages vitepress --binaries --browsers

  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
    Memory: 48.61 GB / 63.73 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.64), ChromiumDev (114.0.1793.0)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: ^1.0.0-alpha.51 => 1.0.0-alpha.75
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-04-30 11:49
Duplicate of #2306

**Closed by brc-dd** 2023-04-30 11:49 UTC
Labels: bug: pending triage
