### ISSUE TITLE
Validate anchor links

### ISSUE THREAD

**Issue by 0x009922** [vuejs/vitepress#2176] opened 2023-03-31 15:50 UTC
### Is your feature request related to a problem? Please describe.

We have a relatively large documentation project with a lot of links between pages. The fact that Vitepress validates inter-document links and fails to build if there are errors while printing detailed information - that's great.

However, it doesn't validate links to anchors within pages, like `refer to [Schema API](./api.md#schema)`. IDEs  (VS Code & Web Storm) can't do this as well, also taking into account that they might have their own "slugify" mechanism for anchors. Also, I can't find markdown linting for that.

### Describe the solution you'd like

I did some research, and I found that it is now possible to get anchors data with the `markdown.anchor.callback` configuration option. I can't build my own validation on top of that because this callback doesn't give any information about the page it is executed for. I think Vitepress can use this option internally to collect all anchors for each page and validate all inter-page (and even in-page!) anchor links and throw an error / print a warning / give an opportunity to configure the behaviour for that case.

I believe that this feature will improve the quality of Vitepress-based projects and will help developers keep anchor links up-to-date. Though, there might be design limitations I am not aware of that don't allow this feature to exist, at least as a default behaviour.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment] 2023-03-31 15:55
Duplicate of #646

**Closed** 2023-03-31 15:55 UTC

**Comment by brc-dd** [comment] 2023-03-31 15:57
Is there any reference on markdown.anchor.callback that you might share?

**Comment by 0x009922** [comment] 2023-04-03 05:17
@brc-dd, here is the reference on `markdown` in Vitepress docs: ﻿﻿https://vitepress.dev/reference/site-config#markdown. There you can find the `.anchor` field. There you can follow the docs for `markdown-it-anchor` plugin: https://github.com/valeriangalliat/markdown-it-anchor#usage. And there you can find the `callback` field.
